src/main/java/com/cloudant/client/api/CloudantClient.java, src/test/java/com/cloudant/tests/DatabaseTest.java, src/test/java/com/cloudant/tests/IndexTests.java, src/test/java/com/cloudant/tests/ReplicationTest.java, src/test/java/com/cloudant/tests/ReplicatorTest.java, src/test/java/com/cloudant/tests/SearchTests.java, src/test/java/com/cloudant/tests/util/Utils.java
=> account parameter in CloudantClient constructor can be a full URI to support cloudant local

CONTRIBUTING.md
Initial contributing guide, inspired by sync-android's contributing.md
reviewer @mikerhodes 
=> Inital Contributing guide

CHANGES.md, src/main/java/com/cloudant/client/api/CloudantClient.java, src/main/java/com/cloudant/client/api/model/ConnectOptions.java, src/main/java/org/lightcouch/CouchDbClient.java, src/main/java/org/lightcouch/CouchDbProperties.java
See https://github.com/cloudant/java-cloudant/pull/57
=> Add get/setAuthenticatedModeSSLSocketFactory configuration option.

.idea/codeStyleSettings.xml, src/main/java/com/cloudant/client/api/CloudantClient.java, src/main/java/com/cloudant/client/api/Database.java, src/main/java/com/cloudant/client/api/DbDesign.java, src/main/java/com/cloudant/client/api/Replication.java, src/main/java/com/cloudant/client/api/Replicator.java, src/main/java/com/cloudant/client/api/Search.java, src/main/java/com/cloudant/client/api/View.java, src/main/java/com/cloudant/client/api/model/Attachment.java, src/main/java/com/cloudant/client/api/model/Response.java, src/main/java/org/lightcouch/CouchDbException.java
*What*
Resolve doclint javadoc validation errors so java-cloudant can build on Java 8 with default settings
*How*
Removed invalid javadoc to pass Java 8 doclint validation
Fixed codestyle to not insert invalid <p/> elements during formatting.
*Testing*
Clean gradle builds with javadoc on Java 8
=> Fix javadoc build errors for Java 8

README.md, src/main/java/com/cloudant/client/api/CloudantClient.java
*What*
Update the `README.md` to address the questions raised in #100 
reviewer @snowch - https://github.com/cloudant/java-cloudant/issues/100#issuecomment-146011430
=> 51337 cxn pool doc

README.md
Some of the TOC entries were broken, also the advanced options were a bit hidden before so adding them to the main TOC.
=> Fix and improve TOC

src/main/java/com/cloudant/client/api/CloudantClient.java, src/main/java/com/cloudant/client/api/model/ConnectOptions.java, src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java, src/main/java/com/cloudant/client/org/lightcouch/CouchDbConfig.java, src/main/java/com/cloudant/client/org/lightcouch/CouchDbProperties.java, src/main/java/com/cloudant/http/HttpConnection.java, src/main/java/com/cloudant/http/interceptors/BasicAuthInterceptor.java, src/main/java/com/cloudant/http/interceptors/ProxyAuthInterceptor.java, src/test/java/com/cloudant/tests/HttpProxyTest.java
*What*
Add proxy support
*How*
Add `ConnectOptions` for proxy url, user and password.
Add a proxy auth interceptor.
Open connections using a `java.net.Proxy` when a proxy has been set.
*Testing*
Added a new test case that checks requests are sent to the proxy address and that the auth header is ok.
=> 53035 http proxy

build.gradle, src/main/java/com/cloudant/client/api/CloudantClient.java, src/main/java/com/cloudant/client/api/model/ConnectOptions.java, src/main/java/com/cloudant/http/interceptors/TimeoutCustomizationInterceptor.java, src/test/java/com/cloudant/tests/CloudantClientHelper.java, src/test/java/com/cloudant/tests/CloudantClientTests.java, src/test/java/com/cloudant/tests/HttpProxyTest.java, src/test/java/com/cloudant/tests/util/SingleRequestHttpServer.java
*What*
Enable timeout customization for `HttpConnection`
*How*
Created a `TimeoutCustomizationInterceptor`.
Changed `ConnectOptions` for timeouts.
Constructed a `TimeoutCustomizationInterceptor` from the options and added it to the list of interceptors.
*Testing*
New tests for read and connect timeouts.
=> 53034 timeout interceptor

src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
*What*
Improve CouchDbClient's `responseToInputStream` exception handling.
*How*
Throw `PreconditionFailedException` when response status code is 412.
In else block, if `fromJson` deserialization fails:
Catch the exception and create a new `CouchDbException` with the response message and code. 
Or, if deserialization returns null:
Create a new `CouchDbException` in `finally` block.
=> Improve responseToInputStream exception handling

.travis.yml, build.gradle, src/main/java/com/cloudant/client/api/Database.java, src/main/java/com/cloudant/client/api/Search.java, src/main/java/com/cloudant/client/org/lightcouch/CouchDatabaseBase.java, src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java, src/main/java/com/cloudant/client/org/lightcouch/CouchDbConfig.java, src/main/java/com/cloudant/client/org/lightcouch/CouchDbProperties.java, src/main/java/com/cloudant/client/org/lightcouch/Replication.java, src/main/java/com/cloudant/http/HttpConnection.java, src/test/java/com/cloudant/tests/BulkDocumentTest.java, src/test/java/com/cloudant/tests/ChangeNotificationsTest.java, src/test/java/com/cloudant/tests/ClientLoadTest.java, src/test/java/com/cloudant/tests/CloudantClientTests.java, src/test/java/com/cloudant/tests/DBServerTest.java, src/test/java/com/cloudant/tests/HttpTest.java, src/test/java/com/cloudant/tests/util/SimpleHttpServer.java, src/test/java/com/cloudant/tests/util/Utils.java
*What*
Complete the Apache HttpClient replacement work
*How*
* Removed Apache HttpClient dependency from gradle
* Removed Apache commons-logging
* Added support for deserializing the error stream into `CouchDbException` subclasses, which in some cases adds additional useful info to the exception.
* Removed the code in `HttpConnection` that was disabling the JVM persistent http connections
*Testing*
* Minor test code cleanups
* Added new test for `Expect: 100-continue` behaviour
* Changed test JVM to `openjdk7`
=> 48522 5 tidy up

src/test/java/com/cloudant/tests/DesignDocumentsTest.java
*What*
Fixes #124 - intermittent failures in dbcopy test
*How*
Added retries to the document verification in the copied database to allow time for cluster replication to complete.
*Testing*
`com.cloudant.tests.DesignDocumentsTest#dbCopy` is updated and passes.
=> Added retries to dbcopy test

src/test/java/com/cloudant/tests/ResponseTest.java
*What*
Fixes #169 for the Cloudant service test `testNonJsonErrorStream` failing.
*How*
Added a flag to only turn on the bad headers for part of the test, so that they don't impact the setup/teardown of the session.
*Testing*
The `com.cloudant.tests.ResponseTest.testNonJsonErrorStream` now passes again.
=> Fix testNonJsonErrorStream test

src/test/java/com/cloudant/tests/IndexTests.java
*What*
Currently the IndexTests perform a lot of operations within a single method which makes it awkward to debug. It would be better to break it down into multiple tests so we can easily identify which part is not working in the event of a test failure.
Issue #138.
*How*
- Split indexTestAll case into separate test cases
- Create indexes and json map in setUp
*Testing*
Existing test cases split up.
=> Refactor IndexTests

CONTRIBUTING.md
Update Contributing to include CLA which is required for all external contributions
Fixes #188
=> Update Contributing to include CLA

src/test/java/com/cloudant/tests/AttachmentsTest.java
*What*
Added a test for saving a new attachment to an existing doc
*How*
Create a document and save it.
Then create an attachment and save it to the document.
Assert that the attachment is correctly saved.
*Testing*
Ran new test against CouchDb and Cloudant service.
=> Added a test for saving a new attachment to an existing doc

CHANGES.md, overview.html
*What*
Added logging info
*How*
Added logging section to the project's root javadoc `overview.html` which appears on the javadoc index page.
*Testing*
N/A documentation.
reviewer: @alfinkel
reviewer: @tomblench
=> Added logging information to overview.html

CHANGES.md, cloudant-client/overview.html
Fixed method names in overview example.
Corrected method names: setUsername() and setPassword() to username()
and password() in Cloudant service example.
Documentation change.
@brad1181 
Fixes #237
=> Fixed error in overview documentation

CHANGES.md, cloudant-client/src/main/java/com/cloudant/client/api/Replication.java, cloudant-client/src/test/java/com/cloudant/tests/CloudantClientHelper.java
Updated doc on replication class.
Updated test helper to URL encode creds.
=> Replication doc

CHANGES.md, cloudant-client/build.gradle, cloudant-client/overview.html, cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java, cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java, cloudant-client/src/test/java/com/cloudant/tests/LoggingTest.java, cloudant-http/src/main/java/com/cloudant/http/HttpConnection.java, cloudant-http/src/main/java/com/cloudant/http/internal/DefaultHttpUrlConnectionFactory.java, cloudant-http/src/main/java/com/cloudant/http/internal/ok/OkHttpClientHttpUrlConnectionFactory.java, logging.properties
Added additional logging
Added a documented example logging.properties file and included it in javadoc.
Added more logging to `HttpConnection` including request/response URL and method at level `FINE`
and request/response headers at level `FINER`.
Added filters `com.cloudant.http.filter.method` and `com.cloudant.http.filter.url` to enable selective logging from `HttpConnection`.
Added a log message prefix for `HttpConnection` so that multiple interleaved requests/responses can be associated.
Added `ClientBuilder` configuration logging.
Added client init config logging.
Updated documentation for logging.
Added new `LoggingTests` class to check the new logging works.
Also did some manual testing.
Fixes #140
=> 140 logging

README.md
Added `Caching, Encryption, and Compression` info to README with links to other libraries.
reviewer @aruniyengar
=> Added caching, encryption, compression info to README

cloudant-client/src/test/java/com/cloudant/tests/ResponseTest.java
Updated HTML response test
New versions of Cloudant return JSON instead of HTML for these error cases the test is updated for this by asserting response codes and error message from JSON instead of looking for `<html>` tag.
Renamed test from `testNonJsonErrorStream` to `testJsonErrorStreamFromLB`.
=> Updated HTML error response test

CHANGES.md, cloudant-client/src/main/java/com/cloudant/client/api/views/MultipleRequestBuilder.java, cloudant-client/src/test/java/com/cloudant/tests/ViewsTest.java
Added builder methods for `reduce` related parameters when using view multiple requests.
Added `SettableViewParameters.Reduceable` interface to `MultipleRequestBuilder` interface.
Added a new test that uses reduce with `MultipleRequestBuilder`.
Fixes #272
=> 272 reduceable multi

CHANGES.md, cloudant-client/src/main/java/com/cloudant/client/api/DesignDocumentManager.java
Close file stream in DesignDocumentManager
Close file stream in `finally` block.
Fixes #308
=> Close DesignDocument FileStream

cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java, cloudant-http/src/main/java/com/cloudant/http/interceptors/BasicAuthInterceptor.java
Allow BasicAuthInterceptor to be created with username and password.
Add factory method `createFromCredentials` to `BasicAuthInterceptor`.
Includes additional unit test.
Fixes #301.
=> 301 document basic auth interceptor

cloudant-http/src/main/java/com/cloudant/http/internal/ok/OkHelper.java
I had to do something similar to this to work out why the class load was failing.
Added a single trace call to help determine why okhttp was not possible.
trivial...
compiles and code coverage
none
=> make it easier to know why okhttp is not possible

Jenkinsfile
Added matrix coverage to `Jenkinsfile`
Added a common `runTests` method to perform test execution.
Defined test environments of configuration env vars.
Added axes for test coverage matrix.
Enabled additional axes for `master` branch.
No new tests added, tests executed as expected when renaming `master` for this branch.
=> Added matrix coverage to Jenkinsfile

CHANGES.md, cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java, cloudant-client/src/test/java/com/cloudant/tests/HttpIamTest.java, cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java, cloudant-client/src/test/java/com/cloudant/tests/util/MockWebServerResources.java, cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/CookieInterceptor.java, cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/CookieInterceptorBase.java, cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java
_What_
- Move shared functionality into CookieInterceptorBase
- Add iamApiKey option to ClientBuilder
_Testing_
- Add mock test
- TODO add more tests...
=> Add IAM session interceptor

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, DCO1.1.txt, README.md
Updated issues and contributing info
* Updated issues guidance in README
* Updated CONTRIBUTING.md instructions.
* Updated PR template with DCO sign off.
* Added DCO file.
N/A - no code changes.
=> Update to dco

README.md
Added a description of the Bluemix convenience methods to the README.
Added more getting started docs for Bluemix.
Updated `README.md` with additional examples for the `ClientBuilder.bluemix()` and `ClientBuilder.iamApiKey()`
Documentation change, no new tests.
=> Added IAM to README

CHANGES.md, cloudant-client/build.gradle, cloudant-client/src/test/java/com/cloudant/tests/ResponseTest.java, cloudant-http/build.gradle
Upgraded optional OkHttp dependency to 3.8.1.
Updated `build.gradle` files.
Updated `CHANGES.md`.
Existing tests passed bar one that was testing using bad header chars to provoke a specific response. The new version of OkHttp has additional validation of headers, so had to update the test to remove spaces, there are still lots of other bad characters in there that provoke the response.
N/A
=> Okhttp 3.8.1

cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java, cloudant-client/src/test/java/com/cloudant/tests/CloudantClientHelper.java, cloudant-client/src/test/java/com/cloudant/tests/HttpIamTest.java, cloudant-client/src/test/java/com/cloudant/tests/IamSystemPropertyMock.java, cloudant-client/src/test/java/com/cloudant/tests/SessionInterceptorExpiryTests.java, cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java
_What_
Add option to allow execution of tests with  IAM authentication enabled
_How_
Add `test.couch.iam.api.key` `-D` option
_Testing_
Some failing tests to be investigated and fixed or marked ignored in a follow up PR
=> Add test.couch.iam.api.key -D option

cloudant-client/overview.html, cloudant-client/src/main/java/com/cloudant/client/api/Database.java, cloudant-client/src/main/java/com/cloudant/client/api/query/JsonIndex.java, cloudant-client/src/main/java/com/cloudant/client/api/query/QueryBuilder.java, cloudant-client/src/main/java/com/cloudant/client/api/query/TextIndex.java, cloudant-client/src/main/java/com/cloudant/client/api/query/package-info.java, cloudant-client/src/main/java/com/cloudant/client/internal/query/Builder.java, cloudant-client/src/main/java/com/cloudant/client/internal/query/Helpers.java, cloudant-client/src/test/java/com/cloudant/api/query/IndexCreationTests.java, cloudant-client/src/test/java/com/cloudant/tests/IndexTests.java, cloudant-client/src/test/java/com/cloudant/tests/QueryTests.java
Javadoc fixes and clarifications for query improvements branch: better examples and clearer guidance for users browsing documents.
`./gradlew javadoc` runs OK.
=> Query improvements javadoc fixes

CHANGES.md, cloudant-client/src/test/java/com/cloudant/tests/HttpIamTest.java, cloudant-client/src/test/java/com/cloudant/tests/SessionInterceptorExpiryTests.java, cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java
Updated default IAM token URL.
Updated URL to `https://iam.bluemix.net/identity/token`.
Updated tests to use `identity` URL.
N/A
=> Update default IAM token URL

Jenkinsfile, cloudant-client/src/test/java/com/cloudant/tests/CloudantClientHelper.java
Fixed test credentials for matrix build.
Reverted `env.CREDS_ID`.
Removed un-needed `COUCH_IAM_API_KEY`.
Used a temporary commit to enable the matrix build for this branch and all tests passed.
(Note temporary commit now removed for review/merge).
N/A PR opened in response to CI break.
=> Fixed test credentials

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Updated issue and PR templates and contributing file.
=> Updated to latest issue and PR templates

cloudant-client/src/test/java/com/cloudant/tests/SessionInterceptorExpiryTests.java, cloudant-client/src/test/java/com/cloudant/tests/util/MockWebServerResources.java
Fixed timing window in `testNewCookieRequestMadeAfterExpiry`
Fixes #460
There were some truncations from millisecond timestamps from `System.currentTimeMillis()` to cookie-date format which only has 1 second granularity. Under unfavourable circumstances this could reduce the time of the cookie lifetime by up to nearly 2 seconds. Since the test was using a 2 second cookie lifetime occasionally there would be a very small window for the test requests to actually be made before the cookie "expired".
Resolved by:
* Extended mock test cookie lifetime to 3 seconds.
* Moved mock cookie timestamping closer to when the cookie is queued.
Note these are test only changes.
- "No change"
- "No change"
- Modified existing tests as described above.
- Looped test 315 times locally without failure, …
=> Fixed timing window in `testNewCookieRequestMadeAfterExpiry` test

CHANGES.md, cloudant-client/overview.html, cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java, cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java
Update the default IAM token server URL.
No change.
No change.
No change.
No change.
=> Update the default IAM token server URL

CHANGES.md, cloudant-client/src/main/java/com/cloudant/client/api/Replicator.java, cloudant-client/src/main/java/com/cloudant/client/api/query/JsonIndex.java, cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/Replicator.java, cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/ReplicatorDocument.java, cloudant-client/src/test/java/com/cloudant/tests/ReplicatorMockTest.java
Add replication selector support.
```java
client.replicator()
.replicatorDocId(replicatorDocId)
.source(sourceDbUrl)
.target(targetDbUrl)
.selector(eq("_id", "Schwarzenegger"))
.save();
```
Fixes #477.
Added selector option to `Replicator` builder.
Additional getters/setters.
No change.
Additional mock test.
=> Add replication selector support.

CHANGES.md, cloudant-client/src/main/java/com/cloudant/client/api/Changes.java
Updated documentation for blocking behaviour caused by https://github.com/apache/couchdb/issues/985
Fixes #490 
Updated javadoc.
- "No change"
- "No change"
- N/A doc only changes
- "No change"
=> Added documentation note about continuous changes blocking

MIGRATION.md
There have been some questions regarding migration lately. This PR tries to address them.
I clarified some of the questionable topics in this change:
* where users should check the server errors and the authentication errors
* 
I also fixed a link for `Configuring the HTTP client section`
- "No change"
- "No change"
- N/A
- "No change"
=> [MIGRATION] Add note about authentication errors and server errors
