.gitignore
README.md
src/test/resources/cloudant-2-sample.properties
src/test/resources/cloudant-sample.properties

Following the advice in README.md, we don't want to accidentally
check in the test properties file with account credentials!
Renamed the files to "sample" names and updated the docs.

test: rename the test properties to sample names

---

src/main/java/com/cloudant/client/api/Database.java

getFindByIndexBody() generates a JSON array of sort fields in a way that works for one sort field, but fails with more than one field because of missing commas.
Ex:
[{"myField": "asc"}] Valid
[{"myFieldOne": "asc"}{"myFieldTwo": "asc"}] Invalid because of missing comma.
The logic to build the array is inside a foreach loop, including:
if (i > 0 ) {
so.append(",");
}
The loop is missing an incrementer for i so the value is never > 0 and the comma is never inserted.

Database.getFindByIndexBody() generates invalid JSON when >1 sort fields are used

---

src/main/java/com/cloudant/client/api/Database.java
src/main/java/com/cloudant/client/api/Search.java
src/main/java/org/lightcouch/Changes.java
src/main/java/org/lightcouch/CouchDbClientBase.java
src/main/java/org/lightcouch/Replication.java
src/main/java/org/lightcouch/Replicator.java
src/main/java/org/lightcouch/View.java
src/main/java/org/lightcouch/internal/CouchDbUtil.java
src/test/java/com/cloudant/test/main/CloudantTestSuite.java
src/test/java/com/cloudant/tests/UnicodeTest.java

Fixes FB#46770.
This fixes the specific bug identified by the test case included in the bug report: Instantiating an InputStreamReader using the platform's default charset can lead to corruption of non ASCII characters. The fix forces the InputStreamReader to use UTF-8. 
Additionally, all other usages of InputStreamReader have been changed to use UTF-8 instead of the platform default charset.
Note that UTF-8 is required to be supported by every implementation of the Java platform - see under "Standard charsets" here:
http://docs.oracle.com/javase/7/docs/api/java/nio/charset/Charset.html
*TESTING*
The test case from the bug report has been modified to fit the style used by the existing tests and incorporated into the test suite.  It was confirmed using the modified test that prior to the …

46770 character encoding bug

---

.gitignore
src/main/java/com/cloudant/client/api/Database.java
src/main/java/org/lightcouch/CouchDatabaseBase.java
src/main/java/org/lightcouch/Param.java
src/main/java/org/lightcouch/Params.java
src/main/java/org/lightcouch/internal/URIBuilder.java
src/test/java/com/cloudant/tests/SearchTests.java
src/test/java/com/cloudant/tests/UpdateHandlerTest.java

Fixes FB#46986.
Ensures the characters `+`, `=` and `&` are correctly percent encoded when they appear in the query part of a URL.
Replacement of the characters is done in `URIBuilder.build`
*TESTING*
Tests added to ensure correct percent encoding of `+`, `=` and `&`.

46986 queries do not encode +

---

src/test/java/com/cloudant/tests/AttachmentsTest.java
src/test/java/com/cloudant/tests/BulkDocumentTest.java
src/test/java/com/cloudant/tests/ChangeNotificationsTest.java
src/test/java/com/cloudant/tests/DBServerTest.java
src/test/java/com/cloudant/tests/DesignDocumentsTest.java
src/test/java/com/cloudant/tests/DocumentsCRUDTest.java
src/test/java/com/cloudant/tests/IndexTests.java
src/test/java/com/cloudant/tests/ReplicationTest.java
src/test/java/com/cloudant/tests/ReplicatorTest.java
src/test/java/com/cloudant/tests/SearchTests.java
src/test/java/com/cloudant/tests/UpdateHandlerTest.java
src/test/java/com/cloudant/tests/ViewsTest.java

Ensure all tests delete the databases they created during their tear down.
Deleting databases and cleaning up other resources mean that previous test state does not effect the current test run.
Call `deleteDb` method on `CloudantClient` in the `tearDown` method.
Replicator and Replication tests have been disabled because they cause intermittent failures on travis, I've opened a ticket (47545) to investigate and fix this issue.
SearchTests and Updatehandler tests were merged with changes on master, as a result their diff is miss leading.
reviewer : @brynh 
reviewer: @tomblench

Make sure tests clean up after themselves

---

CHANGES.md
README.md
src/main/java/com/cloudant/client/api/CloudantClient.java
src/main/java/org/lightcouch/CouchDbClientBase.java
src/test/java/com/cloudant/tests/AttachmentsTest.java
src/test/java/com/cloudant/tests/BulkDocumentTest.java
src/test/java/com/cloudant/tests/ChangeNotificationsTest.java
src/test/java/com/cloudant/tests/DBServerTest.java
src/test/java/com/cloudant/tests/DatabaseTest.java
src/test/java/com/cloudant/tests/DesignDocumentsTest.java
src/test/java/com/cloudant/tests/DocumentsCRUDTest.java
src/test/java/com/cloudant/tests/IndexTests.java
src/test/java/com/cloudant/tests/ReplicationTest.java
src/test/java/com/cloudant/tests/ReplicatorTest.java
src/test/java/com/cloudant/tests/SearchTests.java
src/test/java/com/cloudant/tests/UnicodeTest.java
src/test/java/com/cloudant/tests/UpdateHandlerTest.java
src/test/java/com/cloudant/tests/ViewsTest.java

Create new Database api and deprecate the previous one.
A string confirming the operation to delete the database is needless, in the context that it is being used.
Create `deleteDB(String dbName)`API in `CloudantClient` and `CouchClientBase` classes.
Deprecate `deleteDB(String dbName, String confirm)` in `CloudantClient` and `CouchClientBase`

Create new delete database api

---

CHANGES.md
src/main/java/org/lightcouch/Params.java
src/main/java/org/lightcouch/View.java
src/main/java/org/lightcouch/internal/URIBuilder.java
src/test/java/com/cloudant/tests/ViewsTest.java

Fixes FB#47056
When using a descending view, `queryPreviousPage` didn't go to the previous page. Also, when calling `queryNextPage` after `queryPreviousPage`, the paging was incorrect.  This PR fixes these paging issues.
A new flag `pagingForwards` has been added to track changes in paging direction, so we know when the paging direction has changed.
`queryNextPage` and `queryPreviousPage` have been refactored to reduce code duplication as there were only minor differences between the methods.
*TESTING*
Tests have been added to verify the paging is correct in ascending and descending views, with multiple changes of direction of paging.

47056 query previous page with descending view

---

build.gradle
src/main/java/org/lightcouch/CouchDbClient.java
src/test/java/com/cloudant/tests/CloudantClientTests.java
src/test/java/com/cloudant/tests/util/SingleRequestHttpServer.java

*What*
Add a User-Agent header to requests of the form:
java-cloudant/1.0.2 [Java (amd64; Windows 7; 6.1) Oracle Corporation; 1.8.0_45; 1.8.0_45-b14]
*How*
* Generate a client.properties file as part of the build containing the agent name and version
* At runtime read the client.properties and combine with JVM system properties
* Add the string to the client request headers
*Testing*
Added a test that validates the code is generating strings of the expected format

Added User-Agent to requests

---

src/test/java/com/cloudant/tests/ReplicationTest.java
src/test/java/com/cloudant/tests/ReplicatorTest.java
src/test/java/com/cloudant/tests/util/Utils.java

*What*
Investigate the intermittent failures of replicator and replication test classes.
*How*
The tests were disabled as part of case 47450.  They required a timing fix which was resolved with Thread.sleep().  Also, the replicator documents used in each test are now removed when the test is complete.
*Testing*
Since these classes are test cases, no additional tests are required.
FogBugz: 47545

Intermittent failures of Replicator and Replication tests

---

build.gradle

*What*
Added debug options to the java compilation
*Why*
Improve the debug experience; fixes #52 
*How*
Added gradle compileJava debug options
*Testing*
Validated that additional debug information is present in compiled jars

Added options for additional debug information

---

CONTRIBUTING.md
src/test/java/com/cloudant/tests/IndexTests.java

*What*
Fixed Replicator and Index tests that were failing against the Cloudant service.
*How*
Remove extraneous prefix from IndexTest
Update documentation to make it clear that the _replicator DB must exist.
*Testing*
Fixes apply to existing tests.

49843 cloudant tests

---

src/main/java/com/cloudant/client/api/Database.java
src/main/java/com/cloudant/client/api/model/FindByIndexOptions.java
src/test/java/com/cloudant/tests/IndexTests.java

*What*
Add support for the Cloudant Query use_index option.
*How*
Add new getters/setters to FindByIndexOptions and append new option to body of `/db/_find` request
*Testing*
Added use of new options in IndexTests.indexTestsAll()

Added support for use_index option

---

src/main/java/org/lightcouch/CouchDbProperties.java

*What*
Increased the default number of max connections to 6 (from 2).
*How*
Added a default value to CouchDbProperties. This makes more sense than adding it to ConnectOptions because that object is only used in non-default cases.
*Testing*
Code exercised by existing tests, no specific testing of the number of connections.

Defaulted max connections to 6

---

CHANGES.md
src/main/java/com/cloudant/client/api/CloudantClient.java
src/main/java/com/cloudant/client/api/Database.java
src/main/java/org/lightcouch/CouchDatabaseBase.java
src/main/java/org/lightcouch/CouchDbClientBase.java
src/main/java/org/lightcouch/PreconditionFailedException.java
src/test/java/com/cloudant/tests/CloudantClientTests.java

*What*
Remove the `GET` calls to a database as part of the instantiation of `Database` objects
*Why*
Some users repeatedly instantiate `Database` objects. The repeated `GET` calls reduce performance, but offer little benefit. Whilst doing the `GET` does validate that the backing DB exists, the DB could easily be deleted between the object instantiation and any subsequent calls anyway. As such it makes more sense to remove the call to `GET` and allow the `NoDocumentException` to be thrown when calls are made against a `Database` object for which the backing DB has been removed or does not exist, rather than at object instantiation time.
*How*
* Remove the dbUri `GET` calls from the `connect()` method
* Refactor `CouchDatabaseBase` to rename `connect()` to `create()` and call it only when …

50101 remove db get

---

src/main/java/org/lightcouch/View.java
src/test/java/com/cloudant/tests/Foo.java
src/test/java/com/cloudant/tests/ViewsTest.java
src/test/resources/design-docs/example/views/boolean/map.js
src/test/resources/design-docs/example/views/boolean_creator_created/map.js
src/test/resources/design-docs/example/views/created/map.js
src/test/resources/design-docs/example/views/created_boolean_creator/map.js
src/test/resources/design-docs/example/views/created_total/map.js
src/test/resources/design-docs/example/views/creator_boolean_total/map.js
src/test/resources/design-docs/example/views/creator_created/map.js
src/test/resources/design-docs/example/views/doc_title/map.js
src/test/resources/design-docs/example/views/quotes_created/map.js
src/test/resources/design-docs/example/views/spaces_created/map.js
src/test/resources/design-docs/example/views/total_created/map.js

*What:*
View’s queryPage doesn’t seem to handle multi-value values (FB 48355)
The queryPage method doesn’t handle views that emit keys such as [“uuid”, 100].
#39 DB view key varargs needs parameter typing (FB 48532)
The key, start key, and end key methods are not able to handle complex keys.  One example is a complex key with multiple integer values i.e. key(2011 10, 15).
*How:*
The queryView method in View’s queryPage had a hard cast of String.  This would cause an exception if an integer value existed in a key from the result rows. To fix this:
The String parameter was changed to Object class to allow for other data types. 
If the key in the result rows is an array of multiple values (i.e. startkey=[“uuid”,100]), the array will be converted into one string and then be added as a …

View's queryPage doesn't seem to handle multi-value values

---

src/test/java/com/cloudant/tests/ViewsTest.java

*What*
* Stop swallowing exceptions in some test cases in `ViewsTest`
* Fix up the code style in the `ViewsTest` class
*How*
Remove try catch blocks, allow exceptions thrown from the `queryPage` method to fail the test.
*Testing*
Existing test code refactor, tests still pass.

Removed try/catch blocks from ViewsTest cases

---

src/main/java/org/lightcouch/internal/URIBuilder.java

*What*
Replace rather than append existing parameters when using the `URIBuilder.query(String name, Object value)` method 
*How*
Call `true` not `false` for the replace argument.
*Testing*
All existing tests continue to pass.

Made URIBuilder query replace existing parameters

---

src/main/java/org/lightcouch/View.java
src/test/java/com/cloudant/tests/ViewsTest.java
src/test/resources/design-docs/example/views/boolean_creator_created/map.js
src/test/resources/design-docs/example/views/created_boolean_creator/map.js
src/test/resources/design-docs/example/views/creator_boolean_total/map.js

*What*:
The queryPage functionality throws an exception for map functions containing a JSON array or JSON object emitted value.
*How*:
In the View class, the method JsonToObject is called to convert the JSON element for value to the specified Java object class type.  The specified class type for value is always String as seen below where the ViewResult is initialized and calls queryPage (line 365 of org.lightcouch.View class):
```
final ViewResult<JsonElement, String, T> vr = queryView(JsonElement.class, String.class, classOfT);
```
This means that the JsonToObject method will always try and convert the Row's value to a String object. And, in the case of emitted values that are JSON objects or arrays, an exception of either "Expected String but was JSON_ARRAY” or "Expected String but was …

50264 queryPage throws an exception for Views that emit value as JSON

---

CHANGES.md
src/main/java/com/cloudant/client/api/model/Page.java
src/main/java/com/cloudant/client/api/model/ViewResult.java
src/main/java/org/lightcouch/View.java
src/test/java/com/cloudant/tests/ViewsTest.java
src/test/resources/design-docs/example/views/boolean_creator_created/map.js
src/test/resources/design-docs/example/views/created_boolean_creator/map.js
src/test/resources/design-docs/example/views/creator_boolean_total/map.js

*What*
Re-introduce the changes from #73 which were reverted because of tests failing against Cloudant service clusters.
Fix the pagination issues arising from using the value of `offset`, which is invalid for cluster scenarios.
*How*
As per PR #73 use `JsonElement` instead of `String` for the value when querying views in `queryPage`
Remove usage of the `offset` value in JSON results from a view.
Refactor the pagination code to pass the page number in metadata so it doesn't need to be calculated from the offset.
*Testing*
All the existing pagination and new tests introduced in #73 now pass.
reviewer @brynh 

50264 50739 querypage

---

src/main/java/com/cloudant/client/api/View.java

*What*
Improve the javadoc for ```com.cloudant.client.api.View.queryView```: https://github.com/cloudant/java-cloudant/issues/36
*How*
Add details and sample code for map function, JSON document result, and ViewResult use case.
Update descriptions for parameters and how they relate to the View.
*Testing*
No tests required.

Improve the javadoc for queryView

---

src/main/java/org/lightcouch/View.java
src/main/java/org/lightcouch/internal/CouchDbUtil.java
src/test/java/com/cloudant/tests/CouchDbUtilTest.java
src/test/java/com/cloudant/tests/SearchTests.java

*What*
The java-cloudant library appears to be exploding because it's having a problem de-serialising results of a search query with include_docs=true where one of the values for the "doc" field appears to be null.
*How*
Add logic to catch null values in JsonToObject method.  If the value of the doc is null, return null.
*Tests*
Cases added in SearchTests and ViewsTest.
Assert that the results contain the doc' null value and no ClassCastException occurs.
FogBugz: 50044

Handle doc:null in Search and View's query results

---

src/main/java/org/lightcouch/CouchDbClient.java

*What*
Always register both `http` and `https` socket factories no matter which protocol the database is using.
*Why*
A proxy could use a different protocol to the database.
*How*
Remove protocol `if` checks and always build a socket factory `Registry` with both `http` and `https`.
*Testing*
Existing tests continue to pass; a manual test of a `http` proxy with `https` database succeeded.

52064 http proxy

---

src/test/java/com/cloudant/tests/ReplicationTest.java
src/test/java/com/cloudant/tests/ReplicatorTest.java
src/test/java/com/cloudant/tests/util/Utils.java

*What*
Improve the `ReplicationTest` and `ReplicatorTest`
*Why*
There are two problems with these tests:
1. The test `com.cloudant.tests.ReplicationTest#replicatorDB` is incorrectly using a replicator document instead of triggering a replication. This is a duplication of the equivalent test method in `ReplicatorTest`.
2. The tests `com.cloudant.tests.Replicat*Test#replication_conflict` nearly always fails when running against the Cloudant service. When running against a cluster trying to instantly read back a document that was just saved may not be successful depending on which node the request gets routed to.
*How*
* Rename the `replicatorDB` test to `replicateDatabaseUsingReplicationTrigger` and change the content to use `replication` not `replicator` (which is already covered in the …

ReplicationTest improvements

---

CHANGES.md
README.md
src/main/java/com/cloudant/client/api/Database.java
src/main/java/com/cloudant/client/api/model/Document.java
src/main/java/com/cloudant/client/api/views/AllDocsRequest.java
src/main/java/com/cloudant/client/api/views/AllDocsResponse.java
src/main/java/com/cloudant/client/internal/views/AllDocsRequestBuilderImpl.java
src/main/java/com/cloudant/client/internal/views/AllDocsRequestResponse.java
src/test/java/com/cloudant/tests/ViewsTest.java

*What*
Use custom interfaces for `_all_docs` requests and responses.
*Why*
Feedback from #90 suggested that it was confusing to have `View*` interfaces to handle `_all_docs` requests.
*How*
Add interfaces for `AllDocsRequest` and `AllDocsResponse` that expose simpler methods for handling an `_all_docs` response.
Since `_all_docs` returns view like structures anyway the implementation is still backed by `View*` objects, but additionally complexity is hidden from the end user (e.g. typing as this is constant for `_all_docs`).
*Testing*
Updated `ViewsTest#allDocs()` to use new methods.

52506 all docs

---

src/test/java/com/cloudant/tests/ChangeNotificationsTest.java
src/test/java/com/cloudant/tests/util/CloudantClientResource.java
src/test/java/com/cloudant/tests/util/DatabaseResource.java

*What*
Use uniquely named databases for `ChangeNotificationsTest` to try and resolve intermittent `NoDocumentException` failures in the travis checks, which appear to be caused by overlap of a single database.
*How*
Create JUnit `ExternalResource` types for both the `CloudantClient` and `Database` objects. This allows `before` and `after` methods to be applied at either the test method or test class level by using the `@Rule` and `@ClassRule` annotations respectively. It has the advantage of keeping the setup and
teardown code for these resources in a single place, allowing for easier enforcement of test best practice (such as using a unique name for a `Database`).
Refactor the `ChangeNotificationsTest` to use these resources.
*Testing*
Existing `ChangeNotificationsTest` pass.
reviewer …

52580 changes test

---

build.gradle
src/main/java/com/cloudant/android/Base64OutputStreamFactory.java
src/main/java/com/cloudant/http/AgentHelper.java
src/main/java/com/cloudant/http/CookieInterceptor.java
src/main/java/com/cloudant/http/Http.java
src/main/java/com/cloudant/http/HttpConnection.java
src/main/java/com/cloudant/http/HttpConnectionInterceptorContext.java
src/main/java/com/cloudant/http/HttpConnectionRequestInterceptor.java
src/main/java/com/cloudant/http/HttpConnectionResponseInterceptor.java

*What*
This is the first part in a series of PRs for replacing the current http dependency of Apache’s `httpclient` with sync-android's `HttpURLConnection`.  Migrating to HttpUrlConnection is required for us to use java-cloudant within sync-android.
*How*
- Move required classes over from sync’s http package
- Call `org.apache.commons.codec.binary.Base64OutputStream` directly instead of sync-android's `Base64OutputStreamFactory`:
https://github.com/cloudant/java-cloudant/blob/48522-1-add-http-classes/src/main/java/com/cloudant/http/HttpConnection.java#L193
- Add required dependencies in build.gradle 
*Tests*
No tests required.
FogBugz: 48522

Replace Apache HttpClient with sync-android's com.cloudant.http

---

src/test/java/com/cloudant/tests/ChangeNotificationsTest.java
src/test/java/com/cloudant/tests/UnicodeTest.java
src/test/java/com/cloudant/tests/util/DatabaseResource.java
src/test/java/com/cloudant/tests/util/TestLog.java

*What*
Refactor the unicode tests for the new HTTP API.
*How*
Replace usage of the Apache HTTP classes in the test methods.
Fix print lines with logging.
Update the test to use the new JUnit rules.
*Testing*
The tests pass after the refactor.

48522 unicode tests

---

CHANGES.md
README.md
build.gradle
src/main/java/org/lightcouch/CouchDbProperties.java

*What*
Add default socket and connection timeouts
*Why*
Having an infinite timeout can cause the client to hang by blocking the connection pool if a response is not received.
*How*
Set 5 minute timeouts as defaults in `CouchDbProperties`.
Upgrade Apache HttpClient from 4.3.3 to 4.3.6 to get a handshake socket timeout fix.
*Testing*
Existing tests pass against local and the Cloudant service.

52852 timeout defaults

---

src/test/java/com/cloudant/tests/ReplicateBaseTest.java
src/test/java/com/cloudant/tests/ReplicationTest.java
src/test/java/com/cloudant/tests/ReplicatorTest.java
src/test/java/com/cloudant/tests/util/DatabaseResource.java

*What*
Dynamically name the databases used by the Replicate tests.
*Why*
Prevent intermittent issues with tests stepping on each other's resources.
*How*
Add a supertype with common setup for the tests that utilizes the JUnit `Rule` based resources.
*Testing*
No new tests, but these tests still pass.

Added test resources to replicate tests

---

src/main/java/com/cloudant/client/api/CloudantClient.java
src/main/java/com/cloudant/client/org/lightcouch/CouchDbProperties.java
src/main/java/com/cloudant/http/interceptors/SSLCustomizerInterceptor.java
src/test/java/com/cloudant/tests/SslAuthenticationTest.java

*What*
Enable SSL customization for `HttpsUrlConnection`.
*How*
Create a `SSLCustomizerInterceptor` that sets appropriate socket factories for `HttpsUrlConnections`.
Initialize an appropriate interceptor based on provided `ConnectOptions`.
*Testing*
Re-enabled the `SslAuthenticationTest`.

53085 ssl setters

---

CHANGES.md
README.md
src/main/java/com/cloudant/client/api/CloudantClient.java
src/main/java/com/cloudant/client/api/model/ConnectOptions.java
src/main/java/org/lightcouch/CouchDbClient.java
src/main/java/org/lightcouch/CouchDbProperties.java

*What*
Add proxy authentication options
*How*
Add proxy user name and password options to ConnectOptions.
Configure the credentials provider for the proxy host.
This is taken from the [proxy-auth](https://github.com/cloudant/java-cloudant/tree/proxy-auth) branch, but adjusted slightly for the latest 1.2 maintenance.

51118 proxy auth

---

src/main/java/com/cloudant/client/api/CloudantClient.java
src/test/java/com/cloudant/tests/CloudantClientTests.java

*What*
Set the port to a default value if it is not supplied in the URL
Fixes #113
*How*
Check if the port value was supplied in the URL and if not get the default for the protocol.
*Testing*
Added new test to assert default ports for `http` and `https` URLs.

Added default ports

---

src/main/java/com/cloudant/client/api/CloudantClient.java
src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
src/main/java/com/cloudant/client/org/lightcouch/CouchDbProperties.java
src/main/java/com/cloudant/client/org/lightcouch/internal/URIBuilder.java
src/test/java/com/cloudant/tests/CloudantClientTests.java
src/test/java/com/cloudant/tests/HttpTest.java

*What*
This is the third part of the PR series for replacing the http dependency from Apache’s httpclient to Java’s HttpURLConnection. This part focuses on updating and enabling the cookie interceptor.  
*How*
- Add cookie interceptor in CloudantClient
- Remove CouchDbProperties constructor with username and password
- Use request and response interceptors for adding cookie
- Remove getters for username and password
- Remove cookieNegativeTest
- Add HttpTest class with cookie auth test case
- Add category RequiresCloudant to testCookieAuthWithoutRetry test case
- Remove all calls to URI's userInfo from lightcouch classes
- Remove getUserInfo in HttpConnection
- Remove current auth cookie code
- Improved error handling when PR 111 is complete
- Update code style
*Testing*
Add cookie …

3rd PR: Add cookie interceptor from sync-android's com.cloudant.http package

---

src/main/java/com/cloudant/http/HttpConnection.java
src/main/java/com/cloudant/http/interceptors/BasicAuthInterceptor.java
src/test/java/com/cloudant/tests/CloudantClientTests.java
src/test/java/com/cloudant/tests/HttpProxyTest.java
src/test/java/com/cloudant/tests/ReplicateBaseTest.java
src/test/java/com/cloudant/tests/ReplicationTest.java
src/test/java/com/cloudant/tests/ReplicatorTest.java
src/test/java/com/cloudant/tests/SslAuthenticationTest.java
src/test/java/com/cloudant/tests/UnicodeTest.java
src/test/java/com/cloudant/tests/util/SimpleHttpServer.java
src/test/java/com/cloudant/tests/util/Utils.java

*What*
A series of fixes for the tests to ensure they pass against the Cloudant service
*How*
Ensure interceptors are invoked by using `client.executeRequest` instead of calling `execute` directly on `HttpConnection` objects.
Fix the `Proxy-Authorization` header and make sure the test actually does an assert.
Remove redundant code from the SSL tests.
Fixed intermittent issues in the replication tests.
New tests for not specifying both user and password.
*Testing*
The tests pass against local CouchDB and the Cloudant service.

48522 service test fixes

---

src/test/java/com/cloudant/tests/ClientLoadTest.java
src/test/java/com/cloudant/tests/CloudantClientHelper.java
src/test/java/com/cloudant/tests/DatabaseTest.java
src/test/java/com/cloudant/tests/DesignDocumentsTest.java
src/test/java/com/cloudant/tests/HttpTest.java
src/test/java/com/cloudant/tests/IndexTests.java
src/test/java/com/cloudant/tests/ReplicateBaseTest.java
src/test/java/com/cloudant/tests/ReplicatorTest.java
src/test/java/com/cloudant/tests/SearchTests.java
src/test/java/com/cloudant/tests/SslAuthenticationTest.java
src/test/java/com/cloudant/tests/util/CloudantClientResource.java
src/test/java/com/cloudant/tests/util/DatabaseResource.java
src/test/java/com/cloudant/tests/util/Utils.java

*What*
Several test cases were added from sync-android's HttpTest and a new basic authentication test
*How*
- Removed user info from CloudantClientHelper SERVER_URL to ensure cookie interceptor is used for testing
- Added new method to ensure user info is provided in replication URLs and HttpTest URLs for tests
*Testing*
Test cases:
- testWriteToServerOk
- testExpect100Continue
- testReadBeforeExecute
- testCookieAuthWithoutRetry
- testBasicAuth

Additional http test cases

---

CHANGES.md
README.md
src/main/java/com/cloudant/client/api/CloudantClient.java
src/main/java/com/cloudant/client/api/Database.java
src/main/java/com/cloudant/client/api/Search.java
src/main/java/com/cloudant/client/internal/views/ViewRequester.java
src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java

*What*
Update the `executeRequest` API for the HTTP replacement
*How*
Use `HttpConnection` instead of `InputStream` so that, for example, status codes and headers can be accessed for custom requests.
Updated the documentation for the new HTTP replacement.
*Testing*
No new tests, existing tests continue to pass.

48522 6 execute request

---

src/main/java/com/cloudant/client/api/CloudantClient.java
src/main/java/com/cloudant/http/HttpConnectionRequestInterceptor.java
src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java
src/test/java/com/cloudant/tests/HttpTest.java
src/test/java/com/cloudant/tests/util/Utils.java

*What*
Fixes #117 - encode the username and password of the `_session` request.
*How*
Apply `x-www-form-urlencoded` encoding to the user and password fields.
*Testing*
Added new test to check encoding.

117 url encode session

---

CHANGES.md
README.md
build.gradle
src/main/java/com/cloudant/client/api/model/ConnectOptions.java
src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
src/main/java/com/cloudant/http/HttpConnection.java
src/main/java/com/cloudant/http/ok/OkHttpClientHttpUrlConnectionFactory.java
src/test/java/com/cloudant/tests/HttpTest.java

*What*
Add support for HTTP connection pooling per `CloudantClient` using `HttpConnection` - fixes #121 
*Why*
The default implementation of `HttpUrlConnection` is pooled at a JVM level and controlled via `http.maxConnections`. If changing the `CloudantClient` connection options altered the JVM wide settings there could be unintended consequences for other applications. Having a per `CloudantClient` instance connection pool is in line with the previous max connections option and allows additional flexibility over a JVM wide setting.
*How*
* Add an optional dependency for OkHttp's URL connection.
* Add a runtime check for the `com.squareup.okhttp.OkUrlFactory` class.
* Provide a `HttpUrlConnectionFactory` interface and default implementation in `HttpConnection`.
* Create an implementation …

121 connection pools

---

src/main/java/com/cloudant/client/api/CloudantClient.java
src/main/java/com/cloudant/client/api/Database.java
src/main/java/com/cloudant/client/api/DbDesign.java

*What*
Remove `get` & `put` methods from `CloudantClient` that just delegated to `CouchDbClient`.
Fixes #126.
*How*
Removed methods, made callers use the already visible `couchDbClient` object.
*Testing*
No new tests needed, existing tests still pass.

126 remove methods

---

src/main/java/com/cloudant/client/internal/util/QueryParameters.java
src/test/java/com/cloudant/tests/ViewsTest.java

*What*
Ensure query parameters are honoured for `_all_docs` requests.
Fixes #142.
*How*
The `AllDocsRequestBuilder` uses a subclass of `ViewQueryParameters` so the `getDeclaredFields()` call in `processParameters()` was not able to see the inherited fields and hence the parameters were not appended to the request.
By using `getFields()` there is visibility of the superclass fields (which have public visibility anyway so there is no need to use `getDeclaredFields()`).
*Testing*
Added a new test for an `_all_docs` request using keys to ensure that parameters are used.

142 alldocs parms

---

src/test/java/com/cloudant/tests/AttachmentsTest.java
src/test/java/com/cloudant/tests/BulkDocumentTest.java
src/test/java/com/cloudant/tests/ClientLoadTest.java
src/test/java/com/cloudant/tests/CloudantClientTests.java
src/test/java/com/cloudant/tests/DBServerTest.java
src/test/java/com/cloudant/tests/DocumentsCRUDTest.java
src/test/java/com/cloudant/tests/HttpProxyTest.java
src/test/java/com/cloudant/tests/HttpTest.java
src/test/java/com/cloudant/tests/ReplicatorTest.java
src/test/java/com/cloudant/tests/UpdateHandlerTest.java
src/test/java/com/cloudant/tests/ViewPaginationTests.java
src/test/java/com/cloudant/tests/ViewsTest.java
src/test/java/com/cloudant/tests/util/CloudantClientResource.java
src/test/java/com/cloudant/tests/util/DatabaseResource.java
src/test/java/com/cloudant/tests/util/Utils.java

*What*
Use dynamically named DBs for testing. Fixes #139.
*How*
Refactored tests to use the DatabaseResource.
Made tests share databases where possible to save time.
Added sanitisation to stop tests exceeding 128 char db names.
Cleaned up unused test code.
*Testing*
No new tests, all tests pass against local CouchDB and Cloudant service.

Refactored tests to use dynamic DB names

---

CHANGES.md
src/main/java/com/cloudant/client/api/CloudantClient.java
src/main/java/com/cloudant/client/api/Database.java
src/main/java/com/cloudant/client/api/model/Response.java
src/main/java/com/cloudant/client/org/lightcouch/CouchDatabaseBase.java
src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
src/main/java/com/cloudant/client/org/lightcouch/Response.java
src/main/java/com/cloudant/client/org/lightcouch/internal/CouchDbUtil.java
src/test/java/com/cloudant/tests/ResponseTest.java

*What*
The Response class does not include the HTTP response code. We should add this information to help people align client behavior to the more general Cloudant documentation.
#136 
*How*
- Add setters for http connection's response code and message to Response class
- Set code and message in executeToResponse and in response list of bulk method
- Remove unnecessary class parameter in getResponseList
*Testing*
Add ResponseTest class for asserting response code in returned Response object and in status code for CouchDbException and subclasses.

Add HTTP response codes to Response objects

---

build.gradle

*What*
Re-include exception classes in javadoc output. Fixes #146.
*How*
Update the javadoc includes and use only include patterns, not a mix of includes and excludes.
*Testing*
Javadoc builds cleanly and exception classes are included.

Include exception types in javadoc

---

CHANGES.md
src/main/java/com/cloudant/client/api/DesignDocumentManager.java
src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
src/main/java/com/cloudant/client/org/lightcouch/internal/CouchDbUtil.java
src/main/java/com/cloudant/http/HttpConnection.java
src/main/java/com/cloudant/http/interceptors/BasicAuthInterceptor.java
src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java
src/test/java/com/cloudant/tests/DocumentsCRUDTest.java

*What*
Always specify `UTF-8` instead of using the default codepage. Fixes #155.
*How*
Find and fix all instances in the codebase that don't specify the codepage.
*Testing*
Added new test for ç, but it would only currently fail if executed on a non `UTF-8` codepage.

155 utf8 encoding

---

build.gradle
findbugs_excludes.xml
src/main/java/com/cloudant/client/api/model/Params.java

*What*
Enable findbugs static analysis as part of the gradle build. This is intended as a start to prevent any new "high" level issues getting added and we can over time reduce the filtering as we clean up issues.
*Why*
Prevent some issues sneaking through, such as the UTF-8 encoding problems identified in #155.
*How*
Added the findbugs plugin to gradle.
Switched on reporting for "high" severity issues only on the main source set at first. Ideally later we can enable other severity issues and include the test code.
Fixed a bad equals method identified by findbugs for `Params`.
Added excludes for a couple of naming issues, which it would be good to resolve, but would require bigger changes.
*Testing*
Runs in the gradle build `check` and therefore is included in Travis CI.
reviewer …

Enable findbugs

---

CHANGES.md
src/main/java/com/cloudant/client/org/lightcouch/ReplicatorDocument.java

*What*
Correct deserialization of `ReplicatorDocument` for object source/target URLs. Fixes #153.
*How*
Changed the source & target fields in `ReplicatorDocument` to`JsonElement` from String so they can support both String or `JsonObject`.
Modified the setters and getters to work with the `JsonElement`.
*Testing*
Resolves the failure of `com.cloudant.tests.ReplicatorTest#replicatorDB` when running against the Cloudant service.

153 rep doc url

---

CHANGES.md
src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java
src/main/java/com/cloudant/http/interceptors/HttpConnectionInterceptorException.java
src/test/java/com/cloudant/tests/HttpTest.java

*What*
Renew the session cookie if a 403 is received for expiry. Fixes #157.
*Why*
Expired cookies from Cloudant generate a 403 (whereas CouchDB 1.6.1 generates a 401).
*How*
Added 403 status code checks to the `CookieInterceptor` and read the error stream to identify if it was an expiry case.
In non-expiry 403 cases a new `HttpConnectionInterceptorException` is thrown that contains the error information read from the error stream. This is necessary because otherwise the error information would be lost in 403 responses that were not due to cookie expiry. This is not ideal, but is the strategic fix that doesn't involve breaking the interceptor APIs.
*Testing*
Added new tests for a 403 in both expiry and non-expiry cases.
reviewer @mikerhodes 

157 cookie renew

---

CHANGES.md
src/main/java/com/cloudant/client/api/views/ViewRequest.java
src/main/java/com/cloudant/client/api/views/ViewResponse.java
src/main/java/com/cloudant/client/internal/views/PageMetadata.java
src/main/java/com/cloudant/client/internal/views/PaginationToken.java
src/main/java/com/cloudant/client/internal/views/ViewQueryParameters.java
src/main/java/com/cloudant/client/internal/views/ViewRequestImpl.java
src/main/java/com/cloudant/client/internal/views/ViewResponseImpl.java
src/test/java/com/cloudant/tests/ViewPaginationTests.java
src/test/java/com/cloudant/tests/util/CheckPagination.java

*What*
Enable 1.x style string parameter based paging for 2.x.
*Why*
Fixes #145. There is a use case for passing a String parameter out of the Java application and avoiding keeping any state. The 2.x style paging relied on keeping `ViewResponse` state.
*How*
Added new methods:
* `ViewResponse.getNextPageToken()`
* `ViewResponse.getPreviousPageToken()`
* `ViewRequest.getResponse(String paginationToken)`
Under the covers this requires serialization to JSON of the `PageMetadata` and some `ViewQueryParameters` (`startkey ` `startkey_docid` `endkey ` `endkey_docid` `descending` ` inclusive_end`) followed by Base64 encoding into the token. The new `PaginationToken` class is used for this.
Methods for manipulating the query parameters for paging were moved from `ViewRequestParameters` to …

145 stateless pagination

---

src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
src/test/java/com/cloudant/tests/CloudantClientTests.java

*What*
Logout session when `client.shutdown()` is called.
*Why*
Fixes #152 - the session should not be left active when the client work is finished.
*How*
Added _session DELETE request to shutdown method.
*Testing*
Added new test with mock server to assert delete request send on
client.shutdown() call.

Added _session DELETE request to shutdown method

---

.travis.yml

*What*
Add JDK8 to the Travis checks.
*Why*
Java 8 checks javadoc more stringently than Java 7.
*Testing*
Travis executed successful builds on both JDKs.

Added jdk8 to travis builds

---

CHANGES.md
src/main/java/com/cloudant/client/internal/util/QueryParameter.java
src/main/java/com/cloudant/client/internal/util/QueryParameters.java
src/main/java/com/cloudant/client/internal/views/PageMetadata.java
src/main/java/com/cloudant/client/internal/views/PaginationToken.java
src/main/java/com/cloudant/client/internal/views/ViewQueryParameters.java
src/test/java/com/cloudant/tests/ViewsTest.java
src/test/java/com/cloudant/tests/util/CheckPagination.java
src/test/java/com/cloudant/tests/util/ContextCollectingInterceptor.java

*What*
Fixes #172 ensuring `int` in a complex keys is not turned into `float` by token pagination.
*How*
Internally use `JsonElement` for keys instead of the type erased parameter `K`. This prevents the `ComplexKey` being treated as an `Object` and preserves the JSON array representing the complex key.
*Testing*
Added a new test to check that `int` in a complex key start key remains an `int` for subsequent pages requested by token.
Enabled extra views for complex key pagination tests that appeared to have been accidentally disabled.
reviewer @alfinkel 

172 complex int

---

CHANGES.md
src/main/java/com/cloudant/client/api/Database.java
src/main/java/com/cloudant/client/api/Search.java
src/main/java/com/cloudant/client/api/model/FindByIndexOptions.java
src/main/java/com/cloudant/client/org/lightcouch/CouchDatabaseBase.java
src/test/java/com/cloudant/tests/IndexTests.java

*What*
Building JSON using string operations is causing several defects. Use the GSON library to assemble the object instead.
Issue #101 
*How*
- Replace string building implementation with GSON objects in Database, Search, and CouchDatabaseBase class
*Testing*
New test cases to assert that invalid JSON will throw a bad request.

Use GSON objects to build JSON and not string operations

---

CHANGES.md
src/main/java/com/cloudant/client/api/Database.java
src/main/java/com/cloudant/client/org/lightcouch/CouchDatabaseBase.java
src/test/java/com/cloudant/tests/UpdateHandlerTest.java
src/test/resources/design-files/example_design_doc.js

*What*
`Database.invokeUpdateHandler` only supports PUT requests.  Passing in an empty or null document Id just returns the error `docId is required`.
This fixes #37 by creating a POST request in the update handler when a null document id exists.
*How*
- If no document ID exists, use POST request in `CouchDatabaseBase.invokeUpdateHandler`
- Add new entry for update handler in example's design document. This is used in new test case.
*Testing*
New POST request test case using uuid.

Support POST requests in invokeUpdateHandler

---

src/main/java/com/cloudant/client/api/Search.java
src/main/java/com/cloudant/client/internal/URIBaseMethods.java
src/test/java/com/cloudant/tests/SearchTests.java

*What*
Support multiple drilldown queries by not replacing existing query.
Issue #174.
*How*
- Add `query(String name, Object value, boolean replace)` to be called by Search's `drilldown` method.
*Tests*
New test case for multiple drilldown queries.

Drilldown query parameter can be specified multiple times

---

src/test/java/com/cloudant/tests/DatabaseTest.java
src/test/java/com/cloudant/tests/HttpTest.java
src/test/java/com/cloudant/tests/SearchTests.java

*What*
Correct `assertEquals` argument order in tests.
*Why*
JUnit assertion failure messages use a string like "expected `<a>` but was `<b>`" so the failure messages are confusing if the objects are provided to `assertEquals` in the incorrect order.
*How*
Reversed some JUnit assertions to be in the correct expected then actual order.
*Testing*
No new tests required, fixed in SearchTests, DatabaseTest and HttpTest.

Corrected assertEquals order in tests

---

src/test/java/com/cloudant/tests/util/DatabaseResource.java

*What*
Made db name length for tests configurable.
*Why*
Some databases use a different max length, so the normal max length of 128 cannot be used.
*How*
Used the system property `test.db.name.length` with a default of 128.
*Testing*
Ran Jenkins build using the new configuration option.

Added db name length configuration

---

src/main/java/com/cloudant/client/api/DatabaseImpl.java
src/main/java/com/cloudant/client/org/lightcouch/CouchDatabaseBase.java

*What*
Remove the POST body request parameter which is not required for `invokeUpdateHandler`.
Fixes issue #37.
*How*
- Remove the POST body parameter in `Database.invokeUpdateHandler` and `CouchDatabaseBase.invokeUpdateHandler`
- Pass null to `CouchDbClient.post`.
*Testing*
No new tests.

Remove postBodyRequest parameter

---

src/main/java/com/cloudant/client/api/Database.java
src/test/java/com/cloudant/tests/IndexTests.java

*What*
Validate that the fix from #101 fixes #137.
*How*
Updated documentation for `Database#findByIndex()`.
Added new tests that use complete JSON object strings for selectors.
*Testing*
Added `IndexTests#testNotNullIndexMovieNameAndYearWithCompleteJsonObjectStringSelector()`.
Added `IndexTests#testNotNullIndexMovieNameAndYearWithCompleteJsonObjectSelectorAsString()`.

137 selector test

---

src/main/java/com/cloudant/client/internal/DatabaseURIHelper.java
src/test/java/com/cloudant/tests/AttachmentsTest.java

*What*
Fixed issue where rev was being added to URL path instead of query for standalone attachment saves
*How*
Added revision ID as “rev” query parameter.
*Testing*
Added new test `com.cloudant.tests.AttachmentsTest#attachmentStandaloneUpdate `for updating an attachment.

Fixed standalone attachment update issue

---

src/main/java/com/cloudant/client/api/Database.java
src/main/java/com/cloudant/client/org/lightcouch/CouchDatabaseBase.java
src/test/java/com/cloudant/tests/AttachmentsTest.java

*What*
Fixes #186 regression when saving an attachment to a new document with a given ID (i.e. null revision) and makes `saveAttachment` match the API documentation.
*How*
* Clarified javadoc for the `Database.saveAttachment` with id & rev method.
* Fixed the implementation to generate a UUID instead of throwing an assertion
failure if `null` is passed as a document ID in line with the documentation.
* Added assertions to ensure that we have one of these three combinations
| docId | docRev |
|----|----|
|`null`|`null`|
|not-empty|null|
|not-empty|not-empty|
*Testing*
* New test for a generating a new document with a generated ID when using `saveAttachment`: `attachmentattachmentStandaloneNullIdNullRev`.
* New test for generating a new document with a supplied ID and an attachment: …

186 null id or rev attachments

---

CHANGES.md
src/main/java/com/cloudant/client/internal/HierarchicalUriComponents.java
src/test/java/com/cloudant/tests/ViewsTest.java

*What*
Fixes #202 encoding `;` in query parameters.
*How*
Added `;` to the list of characters to encode in the `HierarchicalUriComponents.Type#QUERY_PARAM`.
Clarified method documentation on why the characters were chosen.
*Testing*
Added new `ViewTests.testUriReservedCharsInStartKey` that makes requests using all URI reserved characters in a view start key to ensure no `400 bad request` is encountered.

202 query param semicolon

---

src/test/java/com/cloudant/tests/ResponseTest.java
src/test/java/com/cloudant/tests/UnicodeTest.java

*What*
Fixes #206 - intermittent test failures with `202` response.
*How*
Change the assertions in `UnicodeTest` & `ResponseTest` to check for `2XX`.
*Testing*
No new tests, modifications to existing tests.

Updated response code assertions

---

CHANGES.md
src/main/java/com/cloudant/client/api/model/DesignDocument.java
src/test/java/com/cloudant/tests/DesignDocumentTest.java
src/test/java/com/cloudant/tests/DesignDocumentsTest.java

Correct Issue where ddocs would not be updated if only the `indexes` field had changed.
Regenerate DesignDocument#equals and DesignDocument#hashCode to take
account of the indexes field.
New tests added for the `DesignDocument.equals` method in `DesignDocumentTest`, and a test which updates the `indexes` field of a ddoc and saves to the server in `DesignDocumentsTest`.
Fixes #212

Update DesignDocument#equals to include indexes

---

CHANGES.md
src/main/java/com/cloudant/http/HttpConnection.java
src/test/java/com/cloudant/tests/HttpTest.java

Added `InputStreamGenerator` for HTTP request replays.
Added `HttpConnection.InputStreamGenerator` interface.
Deprecated `HttpConnection.setRequestBody(InputStream)` method variants.
Added new tests to `HttpTest`:
`inputStreamRetryString()`
`inputStreamRetryBytes()`
`inputStreamRetry()`
`inputStreamRetryWithLength()`
`inputStreamRetryGenerator()` 
`inputStreamRetryGeneratorWithLength()`

Http InputStreamGenerator

---

src/main/java/com/cloudant/http/HttpConnection.java
src/main/java/com/cloudant/http/Version.java
src/main/java/com/cloudant/library/Version.java
src/test/java/com/cloudant/tests/CloudantClientTests.java

Change how the user-agent is generated for HTTP requests in preparation for the splitting out the HTTP classes as a separate jar.
- Created a new Interface `Version` which contains a single method `getVersionString()` which returns the string to be used as the user-agent. 
- AgentHelper is renamed to Version in the new `com.cloudant.library` package.
- The HTTPConnection will load the class at Runtime and default to the JVM default user-agent if it fails.
No new tests, only modified a test case to use the renamed class and interface method.

Set the User-Agent via a Version object loaded at runtime

---

CHANGES.md
README.md
build.gradle
src/main/java/com/cloudant/http/internal/ok/OkHttpClientHttpUrlConnectionFactory.java

Fixes #215 to prevent `javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure` with okhttp and IBM Java.
Changed the `ConnectionSpec` for okhttp to use the enabled protocols and cipher suites from the JVM rather than the default hardcoded list in okhttp's `MODERN_TLS` spec. This resolves the issue with the cipher suite prefixes not matching and also means that the enabled protocols and cipher suites match for both the okhttp and `HttpURLConnection` cases.
Upgraded okhttp to 2.7.5 to allow use of `allEnabled*` methods on `ConnectionSpec`.
No additional tests, tested as working on IBM Java.
#215

215 cxn spec

---

src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java
src/test/java/com/cloudant/tests/HttpTest.java

Update stored cookie when a Set-Cookie header is received.
Check for the `Set-Cookie` HTTP header, and if its present extract the cookie form its value and replace
the one in memory with the newly issued cookie. Although we already do this for the expiry case it is possible for the server to send a renewed cookie before expiry, so by handling those cases we can avoid the extra round trips of the "expired cookie failed request"/"get new cookie"/"repeat failed request" cycle.
Added an extra test to simulate a `Set-Cookie` header being sent to the client.
@ricellis
- #195

Update stored cookie when a Set-Cookie header is received

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
cloudant-client/src/main/java/com/cloudant/library/LibraryVersion.java
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java
cloudant-http/src/main/java/com/cloudant/http/HttpConnection.java

Some small improvements identified by leaking connections investigation and findbugs.
Ensured stream closed after typed get calls in `CouchDbClient`.
Closed both input and output streams after writing request bodies in `HttpConnection`.
Used more efficient `entrySet` loop when setting request properties in `HttpConnection`.
Renamed `com.cloudant.library.Version` to `com.cloudant.library.LibraryVersion` to avoid potential name clash.
No new tests added, existing tests already exercise these paths.
@rhyshort 
@tomblench

Http cxn close

---

CHANGES.md
build.gradle
cloudant-client/findbugs_excludes.xml
cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java
cloudant-client/src/main/java/com/cloudant/client/api/CloudantClient.java
cloudant-client/src/main/java/com/cloudant/client/api/Database.java
cloudant-client/src/main/java/com/cloudant/client/api/Search.java
cloudant-client/src/main/java/com/cloudant/client/api/model/Index.java
cloudant-client/src/main/java/com/cloudant/client/api/model/Membership.java
cloudant-client/src/main/java/com/cloudant/client/api/model/Params.java
cloudant-client/src/main/java/com/cloudant/client/api/model/ReplicatorDocument.java
cloudant-client/src/main/java/com/cloudant/client/api/model/SearchResult.java
cloudant-client/src/main/java/com/cloudant/client/internal/util/DeserializationTypes.java
cloudant-client/src/main/java/com/cloudant/client/internal/util/SecurityDeserializer.java
cloudant-client/src/main/java/com/cloudant/client/internal/util/ShardDeserializer.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/Changes.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDatabaseBase.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/Document.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/Replicator.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/ReplicatorDocument.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/internal/CouchDbUtil.java
cloudant-client/src/test/java/com/cloudant/tests/CouchDbUtilTest.java
cloudant-client/src/test/java/com/cloudant/tests/DesignDocumentsTest.java
cloudant-client/src/test/java/com/cloudant/tests/ReplicateBaseTest.java
cloudant-http/findbugs_excludes.xml
cloudant-http/src/main/java/com/cloudant/http/internal/Base64OutputStreamFactory.java

Enabled the findbugs low level reporting and fixed or excluded existing medium/low issues.
Renamed `JsonToObject` to `jsonToObject` to meet Java naming conventions 56d79ef.
Fixed potential NPE in `Changes` 76c504c.
Fixed inefficient boxing/toString of integers 91af7f4.
Fixed inefficient concatenation in some `toString` methods bac3fc9.
Fixed inefficient iterators where more efficient `Map.entrySet()`could be used b568c19.
Removed some anonymous inner classes in favour of statics 64d421d.
Removed dead local store from `shutdown()` 82251ec.
Fixed `toLowerCase()` calls that failed to specify a  `Locale` internationalisation issue 8ec2ce9.
Fixed `equals`/`hashcode` for `Document` and `ReplicatorDocument` 5303880.
Fixed risk of arrays being modified when used by reference 64d9f30.
Moved error …

Findbugs low reporting and fixes

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/model/DbInfo.java
cloudant-client/src/main/java/com/cloudant/client/api/model/Task.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/ChangesResult.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbInfo.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/ReplicationResult.java

Updated seq ids to use JSON
Updated the classes:
`ChangesResult`
`ReplicationResult`
`DbInfo`
`CouchDbInfo`
`Task`
to use `JsonElement` internally for storing the sequence ids for compatibility with non-String seq id
(e.g. those used by some versions of Cloudant Local). Return the String representation of JSON for API compatibility. Note that some seq ids are still treated as numbers, but may be updated later if the API changes.
Updated CHANGES.md.
Ran tests successfully with Cloudant Data Layer Local Edition.
#175

Updated seq ids to use JSON

---

build.gradle
cloudant-client/build.gradle
cloudant-http/build.gradle

Fixed gradle for releases with subprojects.
Fixed gradle comments.
Moved optional dependency processing into cloudant-http project.
Updated snapshot version.
Checked optional tag in local and snapshot maven repostories.

Fixed gradle for split artifacts

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/Database.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/internal/CouchDbUtil.java
cloudant-client/src/test/java/com/cloudant/tests/IndexTests.java

Fixed regression where a selector with leading whitespace caused a `JsonParseException`.
Trimmed selector string before parsing.
Added a new test `testNotNullIndexMovieNameAndYearSelectorStringWithSpace` with whitespace at the start (and within) the selector string.

Trimmed selector string before parsing

---

CHANGES.md
cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java
cloudant-http/src/main/java/com/cloudant/http/HttpConnection.java

Changed to use JVM default chunk size.
Changed call to `setChunkedStreamingMode(0)` to use JVM default.
Moved call to before request interceptors to allow the size to be changed in an interceptor if necessary.
Increased size of buffer used for HTTP output stream to avoid artificially limiting the chunk size. It is worth noting that current `HttpURLConnection` implementations appear to treat the chunk size as a preference only and in testing the output buffer size was more likely to be used as the chunk size than the size suggested by `setChunkedStreamingMode()`.
Added new test with chunking `HttpTest#testChunking`.

Changed to use JVM default chunk size

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/DesignDocumentManager.java
cloudant-client/src/main/java/com/cloudant/client/internal/DatabaseURIHelper.java
cloudant-client/src/test/java/com/cloudant/tests/DesignDocumentsTest.java
cloudant-client/src/test/java/com/cloudant/tests/util/Utils.java

Fixed regression where `_design/` had to be specified for `DesignDocumentManager` even though it was documented as being optional.
* Added missing doc on DesignDocumentManager.remove(String, String)
* The optional _design prefix functionality was regressed, ensured that `_design/` is added to design document IDs when using the `DesignDocumentManager` class.
* Since the URI path builder already un-escapes the first “/“ in `_design` or `_local` document IDs there is no need to build the path elements separately so removed that added complexity from `DatabaseURIHelper`.
* Updated `CHANGES.md`.
Added new tests to `DesignDocumentsTest` for optional prefix cases:
* `designDocGetNoPrefix()`
* `designDocGetNoPrefixWithRevision()`
* `designDocRemoveNoPrefix()`
* …

240 dd pfx regr

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/Database.java
cloudant-client/src/main/java/com/cloudant/client/api/DesignDocumentManager.java
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java
cloudant-client/src/test/java/com/cloudant/tests/DesignDocumentsTest.java
cloudant-client/src/test/java/com/cloudant/tests/util/MockWebServerResource.java

Avoid deserializing design documents on remove calls.
Used a `HEAD` request and `ETag` header to get revision information instead of doing a `find()` which did a `GET` of the entire document content plus deserialization.
Code path is covered by the `DesignDocumentsTest#designDocRemoveNoPrefix`.
Added two new tests for exception cases:
* couchDbExceptionIfIOExceptionDuringDDocRemove
* couchDbExceptionIfNoETagOnDDocRemove
This addresses the second part of #239.

239 dd remove rev HEAD

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/Database.java
cloudant-client/src/main/java/com/cloudant/client/api/model/FindByIndexOptions.java
cloudant-client/src/test/java/com/cloudant/tests/IndexTests.java

Fixed regressions introduced in 2.2.0 where:
1. `use_index=[]` being added to requests using `FindByIndexOptions` when `useIndex()` had not been called.
1. `use_index` being specified as an array when it should have been a string for the design document only case.
Changed to use `JsonElement` instead of `JsonArray` to support both
string and array use cases.
Stopped adding to the array if `useIndex` is called more than once,
replace the property instead.
Added the `use_index` option to the request only in cases where
`useIndex` was called instead of adding an empty array.
Added 2 new tests to check the type of the use_index property:
-useIndexDesignDocJsonTypeIsString
-useIndexDesignDocAndIndexNameJsonTypeIsArray
Added a new test to check that the use_index property is not
specified if …

Fixed regressions in use_index option

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/library/LibraryVersion.java
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java

Removed very specific platform version information and reduced length of User-Agent string.
Removed java.runtime.version & os.version property values.
Removed unnecessary “Java” word - we know where the Java info is in the string without it.
Re-ordered the properties so that java.version, is followed by vendor and os name is followed by arch.
Used single `/` separators instead of more complex groupings of `;[]()`.
Updated test checks to match new form.
See case 64095.

Reduced the length of the User-Agent string

---

cloudant-client/src/main/java/com/cloudant/client/api/model/DesignDocument.java

Added documentation to `DesignDocument`
Added examples in class javadoc for `DesignDocument` and `DesignDocument.MapReduce`.
Added descriptions and links to Cloudant documentation for getters/setters in `DesignDocument`.
N/A documentation changes. Javadoc build passes.
Fixes #213

Enhanced documentation for DesignDocument class

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/TooManyRequestsException.java
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java
cloudant-client/src/test/java/com/cloudant/tests/DesignDocumentsTest.java
cloudant-client/src/test/java/com/cloudant/tests/HttpProxyTest.java
cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java
cloudant-client/src/test/java/com/cloudant/tests/SslAuthenticationTest.java
cloudant-client/src/test/java/com/cloudant/tests/util/MockWebServerResources.java
cloudant-http/src/main/java/com/cloudant/http/HttpConnection.java
cloudant-http/src/main/java/com/cloudant/http/interceptors/HttpConnectionInterceptorException.java
cloudant-http/src/main/java/com/cloudant/http/interceptors/RequestLimitInterceptor.java

Added handling for `429 Too many requests` server responses.
* cloudant-http
* Expose the current number of retries from `HttpConnection`.
* Added cause constructor to `HttpConnectionInterceptorException`.
* Added unwrapping of `IOException` from interceptor thrown `HttpConnectionInterceptorException`s.
* Create a `RequestLimitInterceptor` that checks for `429` status codes and sleeps before replaying the request.
* The sleep duration is a doubling backoff starting at 0.25 s and doubling with each retry (up to 10 tries by default) unless a `Retry-After` header was specified by the server in which case that is parsed (as seconds) and used as the duration.
* Whilst it would be nice to reschedule the request rather than sleeping the current `HttpConnection` approach does not have an executor …

60008 http 429 backoff

---

cloudant-client/src/main/java/com/cloudant/client/api/Database.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
cloudant-client/src/test/java/com/cloudant/tests/DatabaseTest.java
cloudant-client/src/test/java/com/cloudant/tests/util/MockWebServerResources.java

Ensured error information is included in setPermissions exceptions.
The issue #226 was opened as a result of a PR comment around the throwing of a `CouchDbException` from the `setPermissions` method without including `error` or `reason` information. Investigation of the code paths involved revealed that the branch that threw that exception should have been unreachable anyway because if `ok` was not `true` in the response JSON then a `CouchDbException` would have been thrown already by the `executeToInputStream` method from a non-2XX response code. So the changes here are primarily removing that unnecessary path and adding some tests.
* Simplified `Database.setPermissions()` error handling by removing unreachable exception path.
* Added new test …

226 error resp

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/DesignDocumentManager.java
cloudant-client/src/test/java/com/cloudant/tests/DesignDocumentsTest.java

Added list method to DesignDocumentManager.
Added `list()` method to `DesignDocumentManager` that performs and all docs request using a start key of `_design/` and an exclusive end key of  `_design0` with doc content included to retrieve all the design documents. They are deserialized using the `getDocsAs(DesignDocument.class)` on the all docs response.
Updated CHANGES.md.
Added test `com.cloudant.tests.DesignDocumentsTest#listDesignDocuments()` to exercise `DesignDocumentManager.list()`.
#193

Added list method to DesignDocumentManager

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/views/SettableViewParameters.java
cloudant-client/src/test/java/com/cloudant/tests/ViewsTest.java

Added STALE_NO constant for default view parameter
Added a constant to represent the default omitted stale parameter case
(i.e. it has a `null` value and can be passed into the `stale()` method).
Added new test `ViewsTest#staleParameterValues` for the various stale parameter cases.
#194

Added STALE_NO constant for default view parameter

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/model/DesignDocument.java
cloudant-client/src/test/java/com/cloudant/tests/DesignDocumentsTest.java
cloudant-client/src/test/resources/design-files/query_design_doc.js

Fixed deserialization of query design documents
Replaced `String` map/reduce fields with `JsonElement` in `DesignDocument.MapReduce` to allow for either a JSON string or JSON object to be stored as a map function.
Default for `JsonElement.toString()` is to enclose JSON string with `"` (i.e. escaped quotes `\"`) in the Java string. Added logic to remove these leading and trailing quotes from JSON string map/reduce functions (i.e. javascript language case) to maintain backwards compatibility with existing behaviour. 
Updated CHANGES.md.
Added tests for serializing and deserializing map functions of string and object types for the javascript and query language design documents.
Fixes #239 (part 1), part 2 was done in #242

Fixed deserialization of query design documents

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/Changes.java
cloudant-client/src/main/java/com/cloudant/client/api/DesignDocumentManager.java
cloudant-client/src/main/java/com/cloudant/client/api/views/SettableViewParameters.java
cloudant-client/src/test/java/com/cloudant/tests/ChangeNotificationsTest.java

Added custom query parameter for changes
Added `Changes.parameter(String, String)` method for adding a custom query parameter.
Apply the arguments of that method to the changes request.
Updated `CHANGES.md`.
Added test for custom parameter `ChangeNotificationsTest#changesCustomParameter` that validates the custom parameter is added to a URL.
Fixes #235

235 changes params

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/CloudantClient.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDatabaseBase.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java

Fixed database create behaviour and documentation.
Fixed documentation for `CloudantClient.database` database creation.
Consolidated database create behaviour into a single method.
Removed unnecessary `GET` from `createDB` method that was preventing the documented `PreconditionFailedException` from propagating to`CloudantClient.createDB`.
Added new test for validating the `PreconditionFailedException` is thrown.
Added new test for validating the `PreconditionFailedException` is thrown when using `createDB` and the database does not exist.
reviewer @rhyshort adding you as you already looked at this anyway
Fixes #258

258 db create

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/internal/CouchDbUtil.java
cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java

Fixed `ClassCastException` for `{"reason": null}` `403` responses.
Changed exception `error` and `reason` assigns to use `getAsString` utility method.
Added check for `JsonNull` to `getAsString` utility method.
Added new tests for 403 with a missing or null `reason` property:
* `handleNonExpiry403NoReason`
* `handleNonExpiry403NullReason`
reviewer: @brynh
Fixes #256

Fixed 403 null reason deserialization

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/internal/CouchDbUtil.java
cloudant-http/src/main/java/com/cloudant/http/HttpConnection.java

Added calls to close response streams in places they were missing.
There were a couple of places where calls to `CouchDbUtil` were not
closing streams. `CouchDbUtil.getAsString` was already closing the
streams, so it makes sense if the rest of the util functions that use
streams do the same.
Added comments to remind users to close InputStreams in various places,
where the streams are returned outside of our control.
Moved stream closes into `finally` blocks to make sure they are called.
* Closed stream in a `finally` for `streamToString`
* Routed response calls in `HttpConnection` through fewer lines
and then moved the remaining `close` into a `finally` block to
make sure it is called.
No new tests added. Existing tests continue to pass.
Fixes #268

Closed streams and documented the need to close

---

gradle/wrapper/gradle-wrapper.properties

Updated gradle wrapper to 2.14.1
Gradle 2.14 had an incremental build issue.
Ran `./gradlew wrapper --gradle-version 2.14.1` added updated files.
Existing build/test uses gradle, still functions.

Updated gradle wrapper to 2.14.1

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/Response.java
cloudant-client/src/test/java/com/cloudant/tests/AttachmentsTest.java
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java
cloudant-client/src/test/java/com/cloudant/tests/HttpProxyTest.java
cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java
cloudant-client/src/test/java/com/cloudant/tests/LoggingTest.java
cloudant-client/src/test/java/com/cloudant/tests/ResponseTest.java
cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java

Consumed and closed response streams to avoid leaking connections.
Made `CookieInterceptor` consume error streams in 4xx response cases.
Made `DELETE _session` request in `client.shutdown()` consume the response stream.
Fixed tests that were not closing connection streams:
* `AttachmentsTest`
* `CloudantClientTests`
* `HttpProxyTest`
* `HttpTest`
* `LoggingTest`
* `ResponseTest`
Fixed `HttpTest.cookieInterceptorURLEncoding` test to use `mockWebServer` field instead of starting and stopping an additional instance.
No more instances of leaked connection message seen in logs.
Fixes #277

277 leaked conns

---

cloudant-client/build.gradle
cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java

Always test both HttpURLConnection implementations with a parameterized test.
Parameterised the `HttpTest` class to test using both `HttpURLConnection`
implementations.
Added JMockit to allow a `MockUp` of `OkHttpClientHttpUrlConnectionFactory` so it is possible to force the default `HttpURLConnection` even when okhttp is on the classpath.
These are test changes, the tests pass for both implementations.

Added parameterised testing for both HttpURLConnection types

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/Database.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDatabaseBase.java
cloudant-client/src/test/java/com/cloudant/tests/AttachmentsTest.java

Added functionality to cloudant-client to remove attachment from a document by attachment name.
Needed ability to remove an attachment from a document by attachment name.
Modeled new functionality after the remove() methods that remove a document from the database. Leveraged functionality already available in the REST API to send a delete request with attachment name and _rev as query parameter (info found at https://docs.cloudant.com/attachments.html#delete).
Added tests to com.cloudant.tests.AttachmentTest:
1) Creates a document, adds an attachment, verifies attachment has been added, and then calls the new removeAttachment method. Asserts the bar.getAttachments() is null after removal.
2) Test variant where …

Added functionality to remove attachment from a document by attachment name.

---

CHANGES.md
cloudant-client/build.gradle
cloudant-client/overview.html
cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbProperties.java
cloudant-client/src/test/java/com/cloudant/tests/HttpProxyTest.java
cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java
cloudant-client/src/test/java/com/cloudant/tests/util/MockWebServerResources.java
cloudant-http/src/main/java/com/cloudant/http/HttpConnection.java
cloudant-http/src/main/java/com/cloudant/http/interceptors/ProxyAuthInterceptor.java
cloudant-http/src/main/java/com/cloudant/http/internal/DefaultHttpUrlConnectionFactory.java
cloudant-http/src/main/java/com/cloudant/http/internal/ok/OkHttpClientHttpUrlConnectionFactory.java

Fixed and documented proxy authentication.
Added proxy authenticator for okhttp case.
Added documentation for `HttpURLConnection` case.
Added throw of `IllegalArgumentException` for https proxy URLs.
Added general proxy documentation and caveats to proxy methods
on `ClientBuilder`.
Changed `HttpProxyTest` to use a real proxy server.
Added parameterized combinations to HttpProxyTest:
- HTTP and HTTPS servers
- okhttp or default HttpURLConnection
- using proxy auth or not
Added additional test for `IllegalArgumentException` if an attempt is made to use an https proxy to the `HttpTest` class.
#282

282 proxy auth

---

CHANGES.md
build.gradle
cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java
cloudant-client/src/test/java/com/cloudant/tests/util/MockWebServerResources.java
cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java

Changed `CookieInterceptor` to use `java.net.CookieManager`
The previous `CookieInterceptor` code failed to account for the possibility of multiple `Set-Cookie` headers being present in a response. It also failed to account for the possibility of multiple cookie values within a single header. Finally and most obviously from #287 it failed to check that the string parsing it was doing was safe. To avoid having to write code for all these scenarios it seemed preferable to use the `java.net.CookieManager` instead, which should be spec compliant.
* Removed our existing cookie/header parsing and used an instance of `java.net.CookieManager` instead.
* Refactored methods and error handling to work with `CookieManager` changes.
* Made the `shouldAttemptCookieRequest` atomic as it is potentially …

Changed CookieInterceptor to use CookieManager

---

CHANGES.md
cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java
cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java

Prevent NPE when intercepting response with no body.
* Added a `null` check for the error stream.
* Stopped converting the stream to a string if it was `null`.
* Added `null` check and reversed condition for `errorString.matches` to avoid NPE if the `errorString` was `null`.
* Changed value of  `toThrow.deserialize` to be `false` if the `errorString` was `null` in the case where a non-expiry 403 needs propagating.
Added new tests, which failed with NPE before fix and now pass:
* `noErrorStream403`
* `noErrorStream401`
Note that the NPE does not happen when using okhttp, but our parameterized tests exercise both options anyway.
Fixes #290

290 cookie error npe

---

CHANGES.md
cloudant-client/build.gradle

Upgraded GSON to 2.7
Updated build.gradle
No test changes, all tests pass
Fixes #292 
No new warnings, in the compiler output, changes also didn't mention any deprecation.

Upgrade GSON to 2.7

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java
cloudant-client/src/test/java/com/cloudant/tests/LoggingTest.java

Added log warnings for long JVM DNS cache TTLs.
Added warning level log messages if the TTL is too high or can't be checked.
* If permission is denied to read the configuration property log a warning.
* If the property can be read and parsed, but is longer than 30 s log a warning.
* If the value is the default setting and a `SecurityManager` is active then log a warning because the TTL is infinite if unconfigured with a `SecurityManager`.
Added tests to validate log output:
dnsNoWarningLessThan30
dnsNoWarning0
dnsWarningForever
dnsNoWarning30
dnsWarning31
dnsWarningPermissionDenied
dnsWarningDefaultWithSecurityManager
Fixes #270

270 dns log

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java
cloudant-http/src/main/java/com/cloudant/http/internal/ok/OkHttpClientHttpUrlConnectionFactory.java
cloudant-http/src/main/java/com/cloudant/http/internal/ok/ProxyAuthenticator.java

Fixed class structure that caused early loading of optional okhttp class.
Moved the `ProxyAuthenticator` from a static internal class to a top level class.
No new tests.
Fixes #294

294 opt okhttp

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
cloudant-client/src/test/java/com/cloudant/tests/HttpProxyTest.java
cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java
cloudant-http/src/main/java/com/cloudant/http/internal/DefaultHttpUrlConnectionFactory.java
cloudant-http/src/main/java/com/cloudant/http/internal/ok/OkHelper.java
cloudant-http/src/main/java/com/cloudant/http/internal/ok/OkHttpClientHttpUrlConnectionFactory.java

Moved `isOkUsable` check into own class to avoid further okhttp `NoClassDefFound` issues.
The complexity of the `OkHttpClientHttpUrlConnectionFactory` increased to
the point where it was challenging to continue maintaining it without
inadvertently loading okhttp classes. Such loads prevents okhttp being
optional.
Added a new `OkHelper` class that has only the `isOkUsable` check.
Fixed the test mocks to match.
Added a new test that uses a special `URLClassLoader` with a reflective
load of `OkHelper` to ensure that okhttp classes aren't accidentally loaded
by the helper.
The 2.6.1 release that should have fixed this problem did not because whilst the manual test of the fix did not include okhttp directly it did use the mock web server which pulled in okhttp. This new test gives us a check …

Moved isOkUsable check into own class

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/internal/views/AllDocsRequestResponse.java
cloudant-client/src/test/java/com/cloudant/tests/ViewsTest.java

Fixed NPE in `AllDocsResponse.getIdsAndRevs`.
Added check for a `null` for `row.getValue()` before adding id/rev to result map.
Updated CHANGES.md.
Added test `com.cloudant.tests.ViewsTest#getIdsAndRevsForTwoNonExistentKeysWithAllDocs`
Fixes #297

Fixed NPE in AllDocsResponse.getIdsAndRevs

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Added URL path during creation Cloudant URL since the path is important to connect Cloudant with a gateway.
Added URL path during URL creation in `ClientBuilder.ClientBuilder()` method. Check if urlPath exist in the URL provided to API and add it to resulting URL.
You can connect to Cloudant with URL with not empty path part now. Like following: <https://testproxy.samplehost.net:443/cloudant/mydb>.
Fixes #305 The ClientBuilder.ClientBuilder(URL url) function removes url's path

305 client build url with path

---

cloudant-client/overview.html
cloudant-client/src/test/java/com/cloudant/tests/HttpProxyTest.java

Updated doc and test for CVE-2016-5597.
* Updated doc to mention `jdk.http.auth.tunneling.disabledSchemes` property and the CVE.
`HttpProxyTest.proxiedRequest`
* Updated test to use `jdk.http.auth.tunneling.disabledSchemes` property.
* Updated test `Authenticator` to only send creds to a proxy.
Test now passes locally on the most recent JVM.
Fixes #314

Updated doc and test for CVE-2016-5597

---

CHANGES.md
README.md
build.gradle
cloudant-client/build.gradle
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
cloudant-client/src/test/java/com/cloudant/tests/ChangeNotificationsTest.java
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientHelper.java
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java
cloudant-client/src/test/java/com/cloudant/tests/DatabaseTest.java
cloudant-client/src/test/java/com/cloudant/tests/DesignDocumentsTest.java
cloudant-client/src/test/java/com/cloudant/tests/HttpProxyTest.java
cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java
cloudant-client/src/test/java/com/cloudant/tests/IndexTests.java
cloudant-client/src/test/java/com/cloudant/tests/LoggingTest.java
cloudant-client/src/test/java/com/cloudant/tests/SslAuthenticationTest.java
cloudant-client/src/test/java/com/cloudant/tests/ViewsTest.java
cloudant-client/src/test/java/com/cloudant/tests/util/HttpFactoryParameterizedTest.java
cloudant-client/src/test/java/com/cloudant/tests/util/MockWebServerResources.java
cloudant-http/build.gradle
cloudant-http/src/main/java/com/cloudant/http/interceptors/SSLCustomizerInterceptor.java
cloudant-http/src/main/java/com/cloudant/http/internal/ok/OkHelper.java
cloudant-http/src/main/java/com/cloudant/http/internal/ok/OkHttpClientHttpUrlConnectionFactory.java
cloudant-http/src/main/java/com/cloudant/http/internal/ok/ProxyAuthenticator.java

Updated optional okhttp dependency version to 3.4.2.
* Changed dependency version to 3.4.2 (including mockwebserver).
* Updated package names.
* Fixed 2.x calls that don’t work in 3.x.
* Used new okhttp client builder.
* Updated authenticator.
* Fix SSLInterceptor NPE
* The spec states returning a non-null (possibly empty) array of issuers and whilst a null works on the default it causes a NPE in some implementations. Whilst I can’t find doc that clearly states it behaviour suggests that the empty array is a special case that doesn’t mean trust none, but trust all.
* Updated `CHANGES.md`.
* Parameterised SSL tests for both HTTP implementation types to ensure that we get SSL coverage of both implementations and don't regress one or the other.
* Added `HttpFactoryParameterizedTest` to …

Updated to okhttp3

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java
cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java
cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java

Preserve path for cookie authentication.
Modify the constructor for `CookieInterceptor` to take the URL that the client was constructed with
to use as the base URL. 
New test `testCookieAuthWithPath` in `HTTPTest`
Fixes #320

Preserve path for cookie authentication.

---

CHANGES.md
cloudant-client/findbugs_excludes.xml
cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java
cloudant-client/src/main/java/com/cloudant/client/internal/util/CloudFoundryServices.java
cloudant-client/src/test/java/com/cloudant/tests/CloudFoundryServiceTest.java

Implement bluemix method that creates a Cloudant client from a VCAP_SERVICES environment variable. This allows easy binding of a service instance to a Cloud Foundry application.
Parse the VCAP_SERVICES environment variable as JSON for necessary configuration required to create a Cloudant client.
Includes additional unit tests.
Fixes #323.

Implement bluemix method to create client from VCAP services env

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java
cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java

Prevented double encoding of URL user info when using `ClientBuilder.url()`.
Added URL decoding to creds extracted from URL.
Clarified documentation on `CookieInterceptor` WRT to URL encoding of credentials.
Updated `CHANGES.md`.
Added special character credentials tests
* Made `MockWebServer` available for all `CloudantClientTests`.
* Added new tests:
- testUserInfoWithSpecials()
- testUserInfoInUrlWithSpecials()
Fixes #325

325 url creds

---

cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java
cloudant-client/src/test/java/com/cloudant/tests/CloudFoundryServiceTest.java

Pass the VCAP_SERVICES variable as an argument rather than pulling it
from the environment. This allows the application to retrieve it from
different sources and avoids the library dictating deployment policy to
the consuming application.
Add additional `vcapServices` argument to bluemix builder.
Updated tests to use new argument.
Fixes #323.

323 pass vcap as builder arg

---

build.gradle

Ensured `VERSION` file has qualified path
Running in the IDE could use a working directory at a lower level than the project root and hence `VERSION` file and therefore throw an error when building.
```
FAILURE: Build failed with an exception.
* Where:
Build file '.../java-cloudant/build.gradle' line: 21
* What went wrong:
A problem occurred evaluating root project 'java-cloudant'.
> VERSION (No such file or directory)
```
Added `rootDir` to `VERSION` file path before reading in `build.gradle`.
Existing tests pass.

Ensured VERSION file has qualified path

---

cloudant-client/src/main/java/com/cloudant/client/api/DesignDocumentManager.java
cloudant-client/src/main/java/com/cloudant/client/api/model/DesignDocument.java

Document that the _id, _rev and full content must match for local &
remote documents to be equal. If the local & remote documents are not
equal then the local document _will_ be saved to the database.
Documentation update.
Nope.
Fixes #307.

Improve documentation for design document synchronization

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/internal/HierarchicalUriComponents.java
cloudant-client/src/test/java/com/cloudant/tests/HierarchicalUriComponentsTest.java

Regard plus sign ("+") as reserved character in URI path and path segment components.
Alter logic so that `type.isAllowed("+") = false` for `PATH` and `PATH_SEGMENT` types. This ensures that the plus sign ("+") is treated as a reserved character and therefore encoded as `%2B`.
Includes additional unit tests.
Fixes #335.

 Regard "+" as reserved character in URI path components

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/Database.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDatabaseBase.java
cloudant-client/src/test/java/com/cloudant/tests/AttachmentsTest.java

Add a method to `GET` standalone attachments.
Reads an attachment from the database, returning an `InputStream`.
Updates unit tests.
Fixes #331.

Add a method to GET standalone attachments

---

CHANGES.md
cloudant-client/.gitignore
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbException.java

Include URL in the `CouchDbException` exception message (where applicable).
Add a private `url` attribute to `CouchDbException`. The URL can be set via a setter or through an additional constructor. `.getMessage()` now includes the URL (if defined).
No additional tests.
Fixes #304.

Include URL in the CouchDbException exception message

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
cloudant-http/src/main/java/com/cloudant/http/HttpConnection.java
cloudant-http/src/main/java/com/cloudant/http/internal/DefaultHttpUrlConnectionFactory.java
cloudant-http/src/main/java/com/cloudant/http/internal/ok/OkHttpClientHttpUrlConnectionFactory.java

Added shutdown for the optional OkHttp client.
Added connection factory shutdown methods.
Whilst https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html states that shutdown isn't necessary, it has been observed that, for example, sample applications can take some time to exit when using OkHttp as the threads shutdown. There are some shutdown procedures documented there that make things faster.
Added OK implementation that:
* Shuts down the dispatcher and awaits termination
* Evicts all the connection pool threads
There are no new tests added for this because I can't think of a good way to test it explicitly within the framework. The `shutdown` is called as part of the tear down of most tests so the code should at least be exercised well.

Okhttp shutdown

---

cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java
cloudant-client/src/test/java/com/cloudant/tests/DesignDocumentsTest.java
cloudant-client/src/test/java/com/cloudant/tests/util/MockWebServerResources.java

Fixed long delay in the `connectionTimeout()` test.
The `connectionTimeout()` test was passing, but taking a lot longer than it should. Refactored to use the loopback address for that test to resolve the issue on some JVMs. On OpenJDK there is no difference between the connect and read timeouts (at least for the way this test provokes a connect timeout), so had to add a read timeout as well to make sure it didn't take 5 minutes.
Removed `SleepingDispatcher` class in favour of using MockWebServer’s `SocketPolicy.NO_RESPONSE`, which was able to recreate the behaviour needed for the timeout tests using the sleeping dispatcher. Refactored those tests as necessary.
Test only changes.

Fixed connect test

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/Search.java
cloudant-client/src/test/java/com/cloudant/tests/SearchTests.java

Add faceted search variable argument to `drillDown` method allowing multiple drill down values to be specified.
_This is a minor version change to the API as it does not break binary compatibility._
`drillDown` method now takes variable argument as `fieldValues`.
Includes additional until test.
- Fixes #350

Support faceted search with multiple values for the drill down

---

.travis.yml

Due to a bug in OpenJDK7, gradlew can't bootstrap and download the gradle jar.
See https://bugs.openjdk.java.net/browse/JDK-8080102 and https://redmine.dataone.org/issues/8101

Remove OpenJDK7 from .travis.yml

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/Database.java
cloudant-client/src/main/java/com/cloudant/client/api/Search.java

Updated javadoc for `search` to clarify that the design document name (without `_design` prefix) and index name should be passed in when performing a query.
No tests required.
#369

369 update search javadoc

---

CHANGES.md
cloudant-client/build.gradle
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java
cloudant-client/src/test/java/com/cloudant/tests/HttpIamTest.java
cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java
cloudant-client/src/test/java/com/cloudant/tests/SessionInterceptorExpiryTests.java
cloudant-http/src/main/java/com/cloudant/http/HttpConnection.java
cloudant-http/src/main/java/com/cloudant/http/interceptors/Replay429Interceptor.java
cloudant-http/src/main/java/com/cloudant/http/internal/Utils.java
cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/CookieInterceptor.java
cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/CookieInterceptorBase.java
cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java

Fixed various connection leaks.
Fixed connection leaks:
* Ensured the error stream is consumed in `CookieInterceptorBase`.
* Added a defensive attempt to cleanup to the `HttpConnection` so any missed consumes will be handled as a last resort.
Renamed some fields from `*Session*` to `*Token*` in the `IamCookieInterceptor` to avoid confusion since they were associated with requests to the token endpoint not the `_iam_session` endpoint.
Existing tests using OkHttp exposed messages in the logs for these leaks.
Fixed tests that were themselves leaking connections:
* `com.cloudant.tests.CloudantClientTests#testUserInfoWithSpecials`.
* `com.cloudant.tests.CloudantClientTests#testUserInfoInUrlWithSpecials`.
* `com.cloudant.tests.CloudantClientTests#testUserInfoInUrl`.
* …

Session connection leaks

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/internal/views/MultipleRequestBuilderImpl.java
cloudant-client/src/test/java/com/cloudant/tests/ViewsTest.java

Fixed `IllegalStateException` not thrown for `build()` before `add()` when no request parameters were used.
Set `isBuildable=true` in instances after `add()`, but `false` on initial creation
and after adding parameters.
Added new `com.cloudant.tests.ViewsTest#multiRequestBuildOnlyAfterAddNoParams` that is similar to `multiRequestBuildOnlyAfterAdd` but tries to build with no request parameters or add called first.
Added some additional permutations.
Fixes #383

Ensured IllegalStateException thrown for view multibuilder

---

CHANGES.md
README.md
cloudant-client/overview.html
cloudant-client/src/main/java/com/cloudant/client/api/Changes.java
cloudant-client/src/main/java/com/cloudant/client/api/CloudantClient.java
cloudant-client/src/main/java/com/cloudant/client/api/Database.java
cloudant-client/src/main/java/com/cloudant/client/api/Search.java
cloudant-client/src/main/java/com/cloudant/client/api/model/DesignDocument.java
cloudant-client/src/main/java/com/cloudant/client/api/model/IndexField.java
cloudant-client/src/main/java/com/cloudant/client/api/views/Key.java
cloudant-client/src/main/java/com/cloudant/client/api/views/SettableViewParameters.java
cloudant-client/src/main/java/com/cloudant/client/api/views/ViewMultipleRequest.java
cloudant-client/src/main/java/com/cloudant/client/api/views/package-info.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/Replication.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/Replicator.java

Updated `docs.cloudant.com` links to the latest Bluemix `console.bluemix.net/docs/` documentation.
- Replaced all deprecated links in library with the appropriate Bluemix doc links
- Replaced `Cloudant for developers` with `Cloudant Learning Center` link
No new tests.

Updated docs.cloudant.com deprecated links throughout library

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/views/AllDocsResponse.java
cloudant-client/src/main/java/com/cloudant/client/api/views/ViewResponse.java
cloudant-client/src/main/java/com/cloudant/client/internal/views/AllDocsRequestResponse.java
cloudant-client/src/main/java/com/cloudant/client/internal/views/RowImpl.java
cloudant-client/src/main/java/com/cloudant/client/internal/views/ViewResponseImpl.java
cloudant-client/src/test/java/com/cloudant/tests/ViewsTest.java

Improved handling of non-existent doc ids in view response.
- Check that row has `doc` key and does not have `error` key
Added `_all_docs` tests with a) only non-existing doc ids and b) an existing and non-existing doc id.
fixes #379

Improve handling of non-existent doc ids in view response

---

cloudant-client/src/main/java/com/cloudant/client/api/Database.java

When there are large number of documents, the array list will resize several times if size is not prefixed. Since the size is already known, the size needs to be fixed while creating the array list.
Added initial size to response array construction.
Bulk method covered by existing code path, core Java ctor does not need testing.
N/A

Use pre-fixed size array list during bulk call

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/Changes.java
cloudant-client/src/test/java/com/cloudant/tests/ChangeNotificationsTest.java

Fix bugs in `Changes.readNextRow()`. Previously it was possible for  `readNextRow()` to hang indefinitely for continuous changes feeds.
Exit the while loop early if the line we read from the stream was null or contains `{"last_seq":`.
In theory `row` should never be null because the stream should block if there is no more data or
send "last_seq" when we get to the end. However, it's a case worth handling so that the loop still
exits even if "last_seq" isn't set.
Added mock server test `changesFeedLastSeq`.
Fixes #390.

Fix bugs in Changes.readNextRow() for continuous changes feeds

---

CHANGES.md
cloudant-client/findbugs_excludes.xml
cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java
cloudant-client/src/main/java/com/cloudant/client/internal/util/CloudFoundryService.java
cloudant-client/src/test/java/com/cloudant/tests/CloudFoundryServiceTest.java

Previously the service name was hard coded as 'cloudantNoSQLDB'. This can now be
customised by passing a `serviceName` parameter to the `ClientBuilder.bluemix`
method.
Includes additional unit tests.
Fixes #391.

Allow custom service name in CloudFoundry VCAP_SERVICES environment variable.

---

cloudant-client/src/main/java/com/cloudant/client/api/query/Expression.java
cloudant-client/src/main/java/com/cloudant/client/api/query/Operation.java
cloudant-client/src/main/java/com/cloudant/client/api/query/OperationOrExpression.java
cloudant-client/src/main/java/com/cloudant/client/api/query/PredicateExpression.java
cloudant-client/src/main/java/com/cloudant/client/api/query/PredicatedOperation.java
cloudant-client/src/main/java/com/cloudant/client/api/query/QueryBuilder.java
cloudant-client/src/main/java/com/cloudant/client/api/query/Type.java
cloudant-client/src/main/java/com/cloudant/client/internal/query/Helpers.java
cloudant-client/src/test/java/com/cloudant/tests/QueryTests.java

Easier generation of `selector` for [Cloudant Query](https://docs.cloudant.com/cloudant_query.html)
Add `QueryBuilder` class and classes for operations and expressions with static helpers for compact and fluent creation of selectors aided by IDE auto-complete. 
See `QueryTests` class (TODO rename?)
See #184
other stuff in the query body:
- ~~fields~~
- ~~sort~~
- ~~limit~~
- ~~skip~~
documentation
- javadoc
- CHANGES
- README

Query selector builder

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java

Added `null` check for `ClientBuilder.url(...)`
Called `CouchDbUtil.assertNotNull`.
Added new unit test for `ClientBuilder.url(null)`.
N/A

Added null check for URL in ClientBuilder

---

Jenkinsfile

Changed to use shared global `gitTagAndPublish`.
Removed existing git tagging code and used new `gitTagAndPublish` configuration.
Tested on fork.
N/A

Changed to global gitTagAndPublish

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/internal/views/ViewResponseImpl.java
cloudant-client/src/test/java/com/cloudant/tests/ViewsTest.java

Prevented some `_all_docs` cases truncating the last response row.
Fixed #411 where `total_rows` < `rows` length in an `_all_docs` response fell into the pagination branch causing a truncated response.
Stopped using `total_rows` as `rowsPerPage` in `ViewResponseImpl`.
Updated `CHANGES.md`.
Added a test for 2 deleted, 2 undeleted docs returned to a `keys`
`_all_docs` request.
Fixes #411

Prevented some _all_docs cases truncating the response

---

cloudant-client/src/main/java/com/cloudant/client/api/Replicator.java

Fix javadoc on the `Replicator` class.
The documentation is misleading because it implies the API is on the `Database` object rather than
the `CloudantClient` object.
N/A
#424 - user was confused by documentation

Fix javadoc on Replicator

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/Database.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDatabaseBase.java
cloudant-client/src/test/java/com/cloudant/tests/BulkDocumentTest.java

Preserve the original value of the `reason` value from the response array in the json returned from `_bulk_docs`. This can be queried through `getReason()`
This allows users to retrieve the message from failed validation functions, etc.
Note that the overall HTTP status code is still preserved in each result document and can be queried through `getStatusCode()`. It is therefore the same across all result documents. It should not be relied upon to detect failure:
"The return code from a successful bulk insertion is 201. The content of the returned structure indicates success or other information messages on a per-document basis." (from the IBM Cloudant documentation).
New test `bulkRejectedByValidation`
See #428

Don't over-write reason for bulk()

---

CHANGES.md
cloudant-client/findbugs_excludes.xml
cloudant-client/src/main/java/com/cloudant/client/api/CloudantClient.java
cloudant-client/src/main/java/com/cloudant/client/api/Database.java
cloudant-client/src/main/java/com/cloudant/client/api/scheduler/SchedulerDocsResponse.java
cloudant-client/src/main/java/com/cloudant/client/api/scheduler/SchedulerJobsResponse.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
cloudant-client/src/test/java/com/cloudant/tests/ReplicatorTest.java
cloudant-client/src/test/java/com/cloudant/tests/SchedulerTests.java
cloudant-client/src/test/java/com/cloudant/tests/util/Utils.java

Add support for `/_scheduler/docs` and `/_scheduler/jobs` endpoints.
Tests will now run correctly on Couch 2.0 with update_docs=false.
Fixed tests in `ReplicatorTest`.

Add extra scheduler endpoints and fix tests

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/views/Key.java
cloudant-client/src/test/java/com/cloudant/tests/ViewsTest.java

Syntactic sugar to allow use of complex key high sentinel value.
`Add ComplexKey.addHighSentinel()`.
Added
`queryPageWithComplexStartEndKeyAndJsonObjectValueUsingEndKey`
`addingAfterEndKeyThrowsError`
#147

Add ComplexKey.addHighSentinel()

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/Database.java
cloudant-client/src/main/java/com/cloudant/client/api/views/AllDocsResponse.java
cloudant-client/src/main/java/com/cloudant/client/api/views/ViewResponse.java
cloudant-client/src/main/java/com/cloudant/client/internal/views/AllDocsRequestBuilderImpl.java
cloudant-client/src/main/java/com/cloudant/client/internal/views/AllDocsRequestImpl.java
cloudant-client/src/main/java/com/cloudant/client/internal/views/AllDocsRequestResponse.java
cloudant-client/src/main/java/com/cloudant/client/internal/views/AllDocsResponseImpl.java
cloudant-client/src/main/java/com/cloudant/client/internal/views/RowImpl.java
cloudant-client/src/main/java/com/cloudant/client/internal/views/ViewMultipleRequester.java
cloudant-client/src/main/java/com/cloudant/client/internal/views/ViewRequestImpl.java
cloudant-client/src/main/java/com/cloudant/client/internal/views/ViewResponseImpl.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/Document.java
cloudant-client/src/test/java/com/cloudant/tests/Foo.java
cloudant-client/src/test/java/com/cloudant/tests/ViewsTest.java

Allow retrieval of `deleted` flag on `all_docs`
Introduce "sparse document" information which can be retrieved even when `include_docs=false` is
set. This allows for retrieval of `id`, `rev`, and `deleted` flag.
Also, add `null` check to `getDocsAs()`: this ensures that attempting to deserialise deleted documents does not prevent retrieval of non-deleted ones.
Added
- `allDocsWithKeysDocDeleted`
- `allDocsWithKeysDocDeletedIncludeDocs`
- `allDocsWithKeysDocDeletedIncludeDocsGetDocsAs`
See #427 
See #440

Allow retrieval of deleted flag on all_docs

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/Replication.java
cloudant-client/src/main/java/com/cloudant/client/api/Replicator.java
cloudant-client/src/main/java/com/cloudant/client/api/model/ReplicatorDocument.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/Replication.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/Replicator.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/ReplicatorDocument.java
cloudant-client/src/test/java/com/cloudant/tests/HttpIamTest.java
cloudant-client/src/test/java/com/cloudant/tests/ReplicationMockTest.java
cloudant-client/src/test/java/com/cloudant/tests/ReplicatorMockTest.java
cloudant-client/src/test/java/com/cloudant/tests/util/MockWebServerResources.java

Support IAM authentication in replications. For example:
- Via `replicator` database:
```java
client.replicator()
.source("https://foo.cloudant.com/src")
.sourceIamApiKey("mysourcedbiamapikey")
.target("https://bar.cloudant.com/tgt")
.targetIamApiKey("mytargetdbiamapikey")
.save();
```
- Via `/_replicate` endpoint:
```
client.replication()
.source("https://foo.cloudant.com/src")
.sourceIamApiKey("mysourcedbiamapikey")
.target("https://bar.cloudant.com/tgt")
.targetIamApiKey("mytargetdbiamapikey")
.trigger();
```
Expose new methods on the underlying replication document classes. These add the required IAM API key fields to the generated replication document JSON.
Example IAM authenticated replication document: …

419 support iam auth in replications

---

CHANGES.md
Jenkinsfile
cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java
cloudant-client/src/main/java/com/cloudant/client/internal/util/CloudFoundryService.java
cloudant-client/src/test/java/com/cloudant/tests/CloudFoundryServiceTest.java
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientHelper.java
cloudant-client/src/test/java/com/cloudant/tests/HttpIamTest.java
cloudant-client/src/test/java/com/cloudant/tests/util/MockWebServerResources.java

Added support for IAM API key to `ClientBuilder.bluemix`.
- Added `apikey` and `host` in  `CloudFoundryService.java`  to instantiate IAM client in CloudFoundryServiceCredentials
- Handle cases when IAM or legacy credentials do not exist
- Updated Jenkinsfile to set IAM Key for VCAP testing
- Added CHANGES entry
- Updated copyrights
Added mock tests for accessing VCAP with IAM credentials, and tests that assert `IllegalArgumentException` is raised when IAM key is missing.
For reviewers:
- With the added change of pulling the IAM key in Jenkins, should we consider "future-proofing" tests by adding a client extension that has the option to build a Cloudant client with IAM e.g. `CloudantClientExtension(boolean …

Added support for IAM API key in bluemix method

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/internal/views/ViewQueryParameters.java
cloudant-client/src/test/java/com/cloudant/tests/ViewsTest.java

Fixed including body parameters with multi view requests.
Fixes #458 
When the `BODY_PARAMETER` type was added it was only added to the `ViewQueryParameters#asRequest()` method and hence they were omitted from the conversion to JSON used by necessity for generating a JSON body for the view multi request POST.
Added `BODY_PARAMETER` type to `ViewQueryParameters#asJson()` map generation.
- "No change"
- "No change"
- Modified existing `multiRequest` test to incldude multiple keys in a request to exercise this path. 
- "No change"

Fixed including body parameters with multi view requests

---

CONTRIBUTING.md
README.md

The  `
- "No change"
- "No change"
- N/A build or packaging only changes
- "No change"

Fixed CONTRIBUTING.md and README.md

---

cloudant-client/build.gradle
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientHelper.java
cloudant-client/src/test/java/com/cloudant/tests/DatabaseTest.java
cloudant-client/src/test/java/com/cloudant/tests/IndexTests.java
cloudant-client/src/test/java/com/cloudant/tests/SearchTests.java

Added a task for running integration tests separately.
A collection of small changes to make it easier to run integration tests outside of Jenkins:
* Corrected test task descriptions identifying which tests run with which task.
* Allowed configuration of credential environment variables plus URL, without having to specify all URL components separately.
* Allow configuration of the replicator source account for tests (i.e. where to replicate `animaldb` and others from).
*Added `integration` task, for all Cloudant database tests.
- "No change"
- Change to test credential passing, but no external security/privacy changes.
- Modified existing tests as above to make it easier to run tests that connect to the database.
- "No change"

Segregate integration tests

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/model/DbInfo.java
cloudant-client/src/test/java/com/cloudant/tests/DbInfoMockTests.java

Add `purge_seq` getter on `DbInfo` class that returns seq as `String`.
Fixes #467.
Deprecate `getPurgeSeq()` and add new getter `getStringPurgeSeq()` that returns a `String`.
- Deprecate `DbInfo#getPurgeSeq()`.
- New getter `DbInfo#getStringPurgeSeq()`.
No change.
Add additional unit tests mocks.
No change.

Add `purge_seq` getter on `DbInfo` class that returns seq as `String`

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java
cloudant-client/src/test/java/com/cloudant/tests/HttpIamTest.java
cloudant-client/src/test/java/com/cloudant/tests/util/MockWebServerResources.java
cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java
cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamServerBasicAuthInterceptor.java

Add option for client to authenticate with IAM token server.
Fixes #471.
Overload the `iamApiKey` method in the client builder so that a client ID and secret can be specified.
No breaking API changes.
No change.
Includes additional mock unit test.
No change.

Add option for client to authenticate with IAM token server.

---

CHANGES.md
cloudant-client/findbugs_excludes.xml
cloudant-client/overview.html
cloudant-client/src/main/java/com/cloudant/client/api/CloudantClient.java
cloudant-client/src/main/java/com/cloudant/client/api/Database.java
cloudant-client/src/main/java/com/cloudant/client/api/Search.java
cloudant-client/src/main/java/com/cloudant/client/api/model/DbInfo.java
cloudant-client/src/main/java/com/cloudant/client/api/model/DesignDocument.java
cloudant-client/src/main/java/com/cloudant/client/api/model/PartitionInfo.java
cloudant-client/src/main/java/com/cloudant/client/api/views/SettableViewParameters.java
cloudant-client/src/main/java/com/cloudant/client/internal/DatabaseURIHelper.java
cloudant-client/src/main/java/com/cloudant/client/internal/views/CommonViewRequestBuilder.java
cloudant-client/src/main/java/com/cloudant/client/internal/views/ViewQueryParameters.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java
cloudant-client/src/test/java/com/cloudant/tests/DatabaseURIHelperTest.java
cloudant-client/src/test/java/com/cloudant/tests/PartitionInfoMockTests.java
cloudant-client/src/test/java/com/cloudant/tests/PartitionedDatabaseTest.java
cloudant-client/src/test/java/com/cloudant/tests/extensions/DatabaseExtension.java

Adds partitioned database support.
Inject `_partition/<partitionKey>` into the request URI when a partition key is specified for the following operations:
- All docs.
- View queries.
- Search queries.
- Find queries.
Also, adds an additional method on the database class to fetch database partition metadata.
_No breaking API changes_.
New API:
- `CloudantClient.createPartitionedDB(String dbName)`
- `Database.query(String partitionKey, String query, final Class<T> classOfT)`
- `Database.search(String partitionKey, String searchIndexId)`
- `Database.partitionInfo(String partitionKey)`
No change.
Added additional tests:
- `PartitionedDatabaseTest.java`: Exercises the new partition querying features against a real Cloudant instance.
- `PartitionInfoMockTests.java`: Verifies mock partition …

Partitioned databases

---

CHANGES.md
cloudant-client/findbugs_excludes.xml
cloudant-client/src/main/java/com/cloudant/client/api/model/DbInfo.java
cloudant-client/src/test/java/com/cloudant/tests/DbInfoMockTests.java

This change adds the following fields to the db info response object for a partitioned database:
```json
"partitioned_indexes": {
"count": 7,
"indexes": {
"search": 1,
"view": 6
},
"limit": 10
}
```
See https://github.com/cloudant/showroom/pull/233.
Add properties to the `PartitionInfo` class allowing the additional fields to be correctly deserialized.
Includes new getters on the `PartitionInfo` class (non-breaking).
No change.
Includes additional mock unit tests.
No change.

Add partition Index count to db info response.

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/model/DbInfo.java
cloudant-client/src/test/java/com/cloudant/tests/DbInfoMockTests.java
cloudant-client/src/test/java/com/cloudant/tests/extensions/MultiExtension.java

Added `long` return of `doc_del_count` to `DbInfo`.
Fixes #481
For some reason the deleted doc count was deserialized into a `String` instead of a `long` and exposed in the API as a `String`.
- Deprecated existing `String com.cloudant.client.api.model.DbInfo#getDocDelCount`
- Added `long com.cloudant.client.api.model.DbInfo#getDocDelCountLong`
- "No change"
- Added new mocked test:
- `com.cloudant.tests.DbInfoMockTests#getDbInfoDocDelCount`
I also noticed a problem with the execution order of our JUnit 5 `MultiExtension`, where the registered extensions were run in the same order before and _after_, but the extensions should be run in reverse order after tests.
- "No change"

481 deleted count

---

CONTRIBUTING.md
Jenkinsfile
cloudant-client/build.gradle
cloudant-client/src/test/java/com/cloudant/tests/CloudFoundryServiceTest.java
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientHelper.java
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java
cloudant-client/src/test/java/com/cloudant/tests/DatabaseTest.java
cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java
cloudant-client/src/test/java/com/cloudant/tests/IndexTests.java
cloudant-client/src/test/java/com/cloudant/tests/ReplicationTest.java
cloudant-client/src/test/java/com/cloudant/tests/ReplicatorTest.java
cloudant-client/src/test/java/com/cloudant/tests/SearchTests.java
cloudant-client/src/test/java/com/cloudant/tests/UpdateHandlerTest.java
cloudant-client/src/test/java/com/cloudant/tests/extensions/DatabaseExtension.java
cloudant-client/src/test/java/com/cloudant/tests/extensions/DisabledWithIam.java
cloudant-client/src/test/java/com/cloudant/tests/extensions/IamAuthCondition.java

Try to run the tests with IAM auth credentials.
Tests to pass.
Tests fail.
* Add `IAM_API_KEY` env var and `test.iam.api.key` property for setting an IAM API key.
* Add a JUnit `ExecutionCondition` and `DisabledWithIam` annotation for skipping tests that cannot work with IAM because they rely on other auth methods (e.g. checking basic or cookie auth).
* Updated replication tests to add IAM auth credentials to replications where necessary, when it is not possible to embed the user info in the URL.
- "No change"
- "No change"
- Modified existing tests because to support IAM auth.
- Used a temp commit to run tests with IAM auth for this branch and they [passed](https://cloudant-sdks-jenkins.swg-devops.com:8443/job/java-cloudant/job/iam-testing/6/testReport/).
- "No change"

Enabled IAM auth for testing

---

CHANGES.md
README.md
cloudant-client/build.gradle
cloudant-http/build.gradle
cloudant-http/src/main/java/com/cloudant/http/internal/ok/ProxyAuthenticator.java

Upgrade optional OkHttp dependency to version 3.12.2
- Updated version in README and in `build.gradle`
- Findbugs fix: Removed conditional block that checks if route.proxy is null
- "No change"
- "No change"
- N/A build or packaging only changes
- "No change"

Upgrade optional OkHttp dependency to version 3.12.2

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/query/QueryBuilder.java
cloudant-client/src/test/java/com/cloudant/tests/QueryTests.java

`QueryBuilder ` will produce an invalid JSON query when providing a single string to the `QueryBuilder.fields()` method. The [CouchDB spec](https://docs.couchdb.org/en/2.3.1/api/database/find.html) specifies that `fields` must be an array, but the `QueryBuilder` creates JSON where `fields` is of type string instead when only a single field is specified.
To Reproduce:
```
String build = new QueryBuilder(eq("director", "Lars von Trier")).fields("age").build();
System.out.println(build);
```
Pre-patch JSON output: `{"selector": {"director": {"$eq": "Lars von Trier"}}, "fields": "age"}`
Trying to run this query in either the Cloudant UI or the CouchBD UI results in an error message stating that fields must be an array:
You can get the same error by submitting this query with the …

QueryBuilder.fields() formatting fix

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/views/AllDocsResponse.java
cloudant-client/src/main/java/com/cloudant/client/internal/views/AllDocsRequestResponse.java
cloudant-client/src/test/java/com/cloudant/tests/ViewsTest.java

I need to be able to make paginated requests to the primary index. This can be done using the `skip` and `limit` parameters and checking the `total_rows` property from the response. However the Java API states `Do not use skip/limit for pagination, instead use ViewRequestBuilder.newPaginatedRequest(Key.Type, Class) .` but it doesn't seem to be possible to use a `ViewRequestBuilder` with the primary index.
I expected the Java API would be a Java wrapper around the underlying REST API and should expose the same data, so I think it is correct to make the `total_rows` property available in the `AllDocsResponse` interface.
The total row count is available in the REST API response but the Java API doesn't provide access. This PR adds total row count getter to `AllDocsResponse` interface and …

Add total row count getter to AllDocsResponse

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/internal/views/ViewMultipleRequester.java

Updated view multi-query to work with CouchDB 3
For PRs without an associated issue and/or test/build issues
Run `com.cloudant.tests.ViewsTest#multiRequest` against CouchDB 3.
Test to pass.
Test fails because POST to `{db}/_design/{ddoc}/_view/{viewname}` with `queries` was deprecated since CouchDB 2.2 and is removed in CouchDB 3.
Replace `POST` of `{ "queries": [...]}` body to `{db}/_design/{ddoc}/_view/{viewname}` with `POST` to `{db}/_design/{ddoc}/_view/{viewname}/queries`.
On `badmatch` failure fallback to original `POST` to maintain compatibility with CouchDB versions < 2.2.
- "No change"
- "No change"
- No new tests because existing tests cover this functionality and test matrix ensures coverage of new and old endpoints.
- "No change"

Multiview request changes to support Couch3

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/model/DbInfo.java
cloudant-client/src/test/java/com/cloudant/tests/DbInfoMockTests.java

Updated `DbInfo` sizes functionality.
Call `db.info().getDiskSize()` on CouchDB 3
Expected to get the actual disk size.
Got `0`.
* Added `DbInfo#getSizes()` for access to improved sizes information from newer Couch releases.
* Corrected existing `DbInfo#getDiskSize()` to work with `sizes` object if `disk_size` is unavailable.
- Added new API model `DbInfo.Sizes`
- "No change"
- Added new tests to `DbInfoMockTests`:
- `getDbInfoDiskSizeZeroWithoutException`
- `getDbInfoDiskSize`
- `getDbInfoDiskSizeFromSizes`
- `getDbInfoSizes`
- "No change"

Dbinfo sizes

---

CHANGES.md
cloudant-client/src/test/java/com/cloudant/tests/HttpTest.java
cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/CookieInterceptorBase.java

Consume and close response body stream for successful session requests.
Fixes #507 
This was regressed by #491 - we used to consume the response body for `_session` requests prior to those changes.
* Added a call to `Utils.collectAndCloseStream` with the response body input stream.
* Allow the potential `IOException` to propagate to the existing `wrapIOException` handler for errors reading response status code or body.
- "No change"
- "No change"
Existing tests are passing.
Added new test `com.cloudant.tests.HttpTest#successfulSessionStreamClose` to assert the response stream is consumed/closed.
- Corrected typo in exception message `reponse` -> `response`

Closed successful session response body stream

---

Jenkinsfile

Temporarily disable the Jenkins test matrix while our matrix test environment is unavailable.
Comment out test matrix axes that we can't currently run. Otherwise the automated release process is gated by the failures.
- "No change"
- "No change"
- Disabled `Jenkinsfile` test matrix
- "No change"

Disable testing matrix

---

CHANGES.md
README.md
cloudant-client/build.gradle
cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java
cloudant-client/src/test/java/com/cloudant/tests/CloudFoundryServiceTest.java
cloudant-client/src/test/java/com/cloudant/tests/HttpProxyTest.java
cloudant-client/src/test/java/com/cloudant/tests/SslAuthenticationTest.java
cloudant-client/src/test/java/com/cloudant/tests/util/HttpFactoryParameterizedTest.java
cloudant-client/src/test/java/com/cloudant/tests/util/Utils.java
cloudant-http/build.gradle

Document the limitations of the options `customSSLSocketFactory` and `disableSSLAuthentication` when using the optional OkHttp dependency and Java 8_252 or newer and ignore certain tests in that environment.
Run `com.cloudant.tests.SslAuthenticationTest#localSslAuthenticationDisabled`
Test to pass.
Test (and 9 similar) failed with:
```
com.cloudant.tests.SslAuthenticationTest > localSslAuthenticationDisabled()[2] FAILED
java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+
at okhttp3.internal.platform.Jdk9Platform.trustManager(Jdk9Platform.java:81)
at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.java:176)
at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:768)
at …
```

Limitations of customSSLSocketFactory and disableSSLAuthentication

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/query/Operation.java
cloudant-client/src/main/java/com/cloudant/client/internal/query/Helpers.java
cloudant-client/src/test/java/com/cloudant/tests/QueryTests.java

Fixes #515
I passed the operator to the `quoteCurly` method and used the array for all the operators except `not`.
- "No change"
- "No change"
- Added new tests:
- `basicSelector2WithOneField` in `QueryTests` for an `$and` operator passed with only one `$eq` expression element
- "No change"

Allow query operators to be used with ONE query expression element

---

Jenkinsfile
cloudant-client/build.gradle
cloudant-client/src/test/java/com/cloudant/tests/CloudFoundryServiceTest.java
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientHelper.java
cloudant-client/src/test/java/com/cloudant/tests/CloudantClientTests.java
cloudant-client/src/test/java/com/cloudant/tests/HttpIamTest.java
cloudant-client/src/test/java/com/cloudant/tests/SessionInterceptorExpiryTests.java
cloudant-client/src/test/java/com/cloudant/tests/extensions/MockIamWebServerExtension.java

Change the test server configuration and allow for overriding the token server used by tests.
Run Jenkins tests with a custom IAM token server.
Tests to pass.
Test failures.
1. Add `TEST_IAM_TOKEN_URL` environment variable
- Update `Jenkinsfile`
- Update `cloudant-client/build.gradle` 
2. Fix tests to work with above (see "Testing" below)
3. Added new env vars and cred IDs to `Jenkinsfile`
- "No change"
- "No change"
- Modified existing tests to support changing IAM token server.
- Map `TEST_IAM_TOKEN_URL` env var into `com.cloudant.client.iamserver` system property for test JVM
- Move test env var mapping to apply to all gradle tasks of type `Test`
- Add `MockIamWebServerExtension` to temporarily change `com.cloudant.client.iamserver` system property during tests using a mock IAM server, …

Update test server config

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/Replication.java
cloudant-client/src/main/java/com/cloudant/client/api/Replicator.java
cloudant-client/src/main/java/com/cloudant/client/api/model/ChangesResult.java
cloudant-client/src/main/java/com/cloudant/client/api/model/ReplicatorDocument.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/Replication.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/Replicator.java
cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/ReplicatorDocument.java
cloudant-client/src/test/java/com/cloudant/tests/ReplicationTest.java
cloudant-client/src/test/java/com/cloudant/tests/ReplicatorTest.java

Fixes #526
`seqs` could be `Integer`s in CouchDB 1.x and `String`s in 2.x, so I changed all the places where they remained `Integer`s to `JsonElement`. With this, both `Integer` and `String` can be used.
- No change
- This behavior can be tested with ITs well, so I just extended ITs with a plus `.sinceSeq(...)` call which is going to use a `seq` from a `{source_db}/_changes` request.
- No change

Type of `sinceSeq` can be also a String besides an Integer

---

CHANGES.md
cloudant-client/src/main/java/com/cloudant/client/api/ClientBuilder.java
cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/CookieInterceptor.java
cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/CookieInterceptorBase.java
cloudant-http/src/main/java/com/cloudant/http/internal/interceptors/IamCookieInterceptor.java

Enable proxy support for cookie session and IAM authentication.
fixes #528 
Extend the `CookieInterceptorBase` constructor with a proxy url parameter.
Update both `IamCookieInterceptor` and `CookieInterceptor` to support new proxy url parameter during initialization.
Manual testing against a local mock server.  The following tests passed:
1) Proxy enabled with request + session auth against local couchdb
2) Proxy enabled with request + session auth against Cloudant
3) Proxy enabled with request + IAM (only with built-in `HttpUrlConnection`) against Cloudant

proxy support for cookie session and IAM authentication

---

MIGRATION.md

My goal was to improve the migration guide dispersing the fog around the support of the retry feature an error handling.
* applied code style on the links for new operations d18ea7181621ee302b6b6edce6752f8e4676dbbd
* fixed incorrect links (8c0294d1ff261987b63e7f288dbcd7b913f74a68):
* `postReplicate` was excluded from new SDKs, so I pointed `replication().trigger()` to the `putReplicationDocument` operation
* link for `postChanges` changed
* the link for `postPartitionFind` has changed
* Added a warning about the error handling 0ac0f56d0dcb89ac1b8109cae913f7cf938cbde1
* Added a note about Replays interceptors replacement 0ac0f56d0dcb89ac1b8109cae913f7cf938cbde1
- "No change"
- "No change"
- N/A build or packaging only changes
- "No change"

Improve migration guide
